@extends('layouts.admin')

@section('title', $discount->name)

@section('content')
    <div class="mb-6 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><a href="{{ route('discounts.index') }}" class="text-sm font-medium text-indigo-700 hover:text-indigo-500">Volver a descuentos</a><div class="mt-3 flex flex-wrap items-center gap-3"><h1 class="text-3xl font-bold tracking-tight">{{ $discount->name }}</h1><x-status-badge :active="$discount->is_active" /></div></div>@can('discounts.manage')<a href="{{ route('discounts.edit', $discount) }}" class="rounded-lg bg-indigo-600 px-4 py-2.5 text-center text-sm font-semibold text-white hover:bg-indigo-500">Editar</a>@endcan</div>
    <div class="grid gap-5 lg:grid-cols-[2fr_1fr]"><section class="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-7"><h2 class="text-lg font-bold">Regla de descuento</h2><dl class="mt-5 grid gap-5 sm:grid-cols-2"><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Tipo</dt><dd class="mt-1 text-slate-800">{{ $discount->type->value === 'percentage' ? 'Porcentaje' : 'Monto fijo' }}</dd></div><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Valor</dt><dd class="mt-1 text-slate-800">{{ number_format((float) $discount->value, 2) }}{{ $discount->type->value === 'percentage' ? '%' : '' }}</dd></div><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Inicio</dt><dd class="mt-1 text-slate-800">{{ $discount->start_date?->format('Y-m-d') ?: 'Sin limite' }}</dd></div><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Fin</dt><dd class="mt-1 text-slate-800">{{ $discount->end_date?->format('Y-m-d') ?: 'Sin limite' }}</dd></div><div class="sm:col-span-2"><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Sucursales</dt><dd class="mt-1 text-slate-800">{{ $discount->branches->pluck('name')->join(', ') ?: 'Todas las sucursales habilitadas para el articulo.' }}</dd></div></dl></section><aside class="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h2 class="text-lg font-bold">Articulos asociados</h2><ul class="mt-4 grid gap-2">@foreach ($discount->thirdPartyItems as $thirdPartyItem)<li><a href="{{ route('third-party-items.show', $thirdPartyItem) }}" class="block rounded-lg bg-slate-50 px-3 py-2 text-sm font-medium text-indigo-700 hover:text-indigo-500">{{ $thirdPartyItem->name }}<span class="block pt-1 text-xs font-normal text-slate-500">{{ $thirdPartyItem->commercialPartner->name }}</span></a></li>@endforeach</ul></aside></div>
    <section class="mt-5 rounded-xl border border-indigo-100 bg-indigo-50 p-5 text-sm text-indigo-950"><h2 class="font-bold">Criterio de aplicacion</h2><p class="mt-2">Al vender un articulo externo, se consideran solo descuentos activos, vigentes y habilitados para la sucursal. Si hay varios, se aplica uno: el que reduzca mas el importe de la linea; en empate, el de menor identificador.</p></section>
    @can('discounts.manage')@if ($discount->is_active)<form method="POST" action="{{ route('discounts.destroy', $discount) }}" class="mt-5" onsubmit="return confirm('Deseas desactivar este descuento?');">@csrf @method('DELETE')<button class="rounded-lg border border-red-300 px-4 py-2.5 text-sm font-semibold text-red-700 hover:bg-red-50">Desactivar</button></form>@endif@endcan
@endsection
