@extends('layouts.admin')

@section('title', $membershipType ? 'Editar tipo de membresía' : 'Nuevo tipo de membresía')

@section('content')
    @php($selectedBenefitIds = old('benefit_ids', $membershipType?->benefits->modelKeys() ?? []))
    <div class="mb-6"><a href="{{ route('membership-types.index') }}" class="text-sm font-medium text-indigo-700 hover:text-indigo-500">← Volver a membresías</a><h1 class="mt-3 text-3xl font-bold tracking-tight">{{ $membershipType ? 'Editar tipo de membresía' : 'Nuevo tipo de membresía' }}</h1></div>
    <form method="POST" action="{{ $membershipType ? route('membership-types.update', $membershipType) : route('membership-types.store') }}" class="max-w-4xl rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-7">@csrf @if ($membershipType) @method('PUT') @endif<div class="grid gap-5 sm:grid-cols-2"><div><label for="name" class="text-sm font-medium text-slate-700">Nombre</label><input id="name" name="name" value="{{ old('name', $membershipType?->name) }}" required class="mt-1 block w-full rounded-lg border-slate-300"><x-field-error name="name" /></div><div><label for="reference_price" class="text-sm font-medium text-slate-700">Precio de referencia</label><input id="reference_price" name="reference_price" type="number" min="0" step="0.01" value="{{ old('reference_price', $membershipType?->reference_price) }}" required class="mt-1 block w-full rounded-lg border-slate-300"><x-field-error name="reference_price" /></div><div class="sm:col-span-2"><label for="description" class="text-sm font-medium text-slate-700">Descripción</label><textarea id="description" name="description" rows="4" class="mt-1 block w-full rounded-lg border-slate-300">{{ old('description', $membershipType?->description) }}</textarea><x-field-error name="description" /></div><fieldset class="sm:col-span-2"><legend class="text-sm font-medium text-slate-700">Beneficios asociados</legend><div class="mt-2 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">@foreach ($benefits as $benefit)<label class="flex items-center gap-2 rounded-lg border border-slate-200 p-3 text-sm"><input type="checkbox" name="benefit_ids[]" value="{{ $benefit->id }}" @checked(in_array($benefit->id, array_map('intval', $selectedBenefitIds), true)) class="rounded border-slate-300 text-indigo-600">{{ $benefit->name }}</label>@endforeach</div><x-field-error name="benefit_ids" /></fieldset><label class="flex items-center gap-2 text-sm text-slate-700 sm:col-span-2"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $membershipType?->is_active ?? true)) class="rounded border-slate-300 text-indigo-600">Tipo activo</label></div><div class="mt-7 flex flex-wrap gap-3"><button type="submit" class="rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-indigo-500">{{ $membershipType ? 'Guardar cambios' : 'Crear tipo' }}</button><a href="{{ $membershipType ? route('membership-types.show', $membershipType) : route('membership-types.index') }}" class="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50">Cancelar</a></div></form>
@endsection
