@extends('layouts.admin')

@section('title', $membershipType->name)

@section('content')
    <div class="mb-6 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><a href="{{ route('membership-types.index') }}" class="text-sm font-medium text-indigo-700 hover:text-indigo-500">← Volver a membresías</a><div class="mt-3 flex flex-wrap items-center gap-3"><h1 class="text-3xl font-bold tracking-tight">{{ $membershipType->name }}</h1><x-status-badge :active="$membershipType->is_active" /></div><p class="mt-2 text-slate-600">Precio de referencia: {{ number_format((float) $membershipType->reference_price, 2) }}</p></div>@can('membership-types.manage')<a href="{{ route('membership-types.edit', $membershipType) }}" class="rounded-lg bg-indigo-600 px-4 py-2.5 text-center text-sm font-semibold text-white hover:bg-indigo-500">Editar</a>@endcan</div>
    <div class="grid gap-5 lg:grid-cols-[2fr_1fr]"><section class="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-7"><h2 class="text-lg font-bold">Descripción</h2><p class="mt-3 whitespace-pre-line text-slate-700">{{ $membershipType->description ?: 'Sin descripción registrada.' }}</p></section><aside class="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h2 class="text-lg font-bold">Beneficios asociados</h2><ul class="mt-4 grid gap-2">@forelse ($membershipType->benefits as $benefit)<li><a href="{{ route('benefits.show', $benefit) }}" class="block rounded-lg bg-slate-50 px-3 py-2 text-sm font-medium text-indigo-700 hover:text-indigo-500">{{ $benefit->name }}</a></li>@empty<li class="text-sm text-slate-500">No hay beneficios asociados.</li>@endforelse</ul></aside></div>
    @can('membership-types.manage')<div class="mt-5 flex flex-wrap gap-3"><form method="POST" action="{{ route('membership-types.toggle-status', $membershipType) }}" onsubmit="return confirm('¿Deseas cambiar el estado de este tipo de membresía?');">@csrf @method('PATCH')<button class="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50">{{ $membershipType->is_active ? 'Desactivar' : 'Activar' }}</button></form>@if ($membershipType->is_active)<form method="POST" action="{{ route('membership-types.destroy', $membershipType) }}" onsubmit="return confirm('¿Deseas desactivar este tipo de membresía?');">@csrf @method('DELETE')<button class="rounded-lg border border-red-300 px-4 py-2.5 text-sm font-semibold text-red-700 hover:bg-red-50">Desactivar</button></form>@endif</div>@endcan
@endsection
