@extends('layouts.admin')

@section('title', 'Referido #'.$referral->id)

@section('content')
    @php($availableRewardAmount = max(0, (float) $referral->reward_amount - $usedRewardAmount))
    <div class="mb-6 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><a href="{{ route('referrals.index') }}" class="text-sm font-medium text-indigo-700 hover:text-indigo-500">Volver a referidos</a><h1 class="mt-3 text-3xl font-bold tracking-tight">Referido #{{ $referral->id }}</h1><p class="mt-2 text-slate-600">Registrado el {{ $referral->created_at->format('d/m/Y') }}</p></div><div class="flex flex-wrap gap-3">@can('referrals.register')@if ($referral->status === \App\ReferralStatus::Pending)<form method="POST" action="{{ route('referrals.activate', $referral) }}">@csrf @method('PATCH')<button class="rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-indigo-500">Validar beneficio</button></form>@endif@endcan @can('referrals.manage')@if ($referral->status !== \App\ReferralStatus::Cancelled)<form method="POST" action="{{ route('referrals.cancel', $referral) }}" onsubmit="return confirm('Deseas cancelar este referido?');">@csrf @method('PATCH')<button class="rounded-lg border border-red-300 px-4 py-2.5 text-sm font-semibold text-red-700 hover:bg-red-50">Cancelar</button></form>@endif@endcan</div></div>
    <div class="grid gap-5 lg:grid-cols-[2fr_1fr]"><section class="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-7"><h2 class="text-lg font-bold">Participantes</h2><dl class="mt-5 grid gap-5 sm:grid-cols-2"><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Referidor</dt><dd class="mt-1"><a href="{{ route('clients.show', $referral->referrer) }}" class="font-medium text-indigo-700 hover:text-indigo-500">{{ $referral->referrer->first_name }} {{ $referral->referrer->last_name }}</a></dd></div><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Referido</dt><dd class="mt-1"><a href="{{ route('clients.show', $referral->referred) }}" class="font-medium text-indigo-700 hover:text-indigo-500">{{ $referral->referred->first_name }} {{ $referral->referred->last_name }}</a></dd></div><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Estado</dt><dd class="mt-1 text-slate-800">{{ ucfirst($referral->status->value) }}</dd></div><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Estado del beneficio</dt><dd class="mt-1 text-slate-800">{{ ucfirst($referral->reward_status->value) }}</dd></div></dl></section><aside class="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h2 class="text-lg font-bold">Beneficio Q100</h2><dl class="mt-4 space-y-3 text-sm"><div class="flex justify-between gap-4"><dt class="text-slate-600">Otorgado</dt><dd>Q{{ number_format((float) $referral->reward_amount, 2) }}</dd></div><div class="flex justify-between gap-4"><dt class="text-slate-600">Usado</dt><dd>Q{{ number_format($usedRewardAmount, 2) }}</dd></div><div class="flex justify-between gap-4 border-t border-slate-200 pt-3 font-bold"><dt>Disponible</dt><dd>Q{{ number_format($availableRewardAmount, 2) }}</dd></div></dl></aside></div>
    <section class="mt-5 overflow-hidden rounded-xl bg-white shadow-sm ring-1 ring-slate-200"><div class="border-b border-slate-200 px-5 py-4"><h2 class="text-lg font-bold">Historial de uso del beneficio</h2></div><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50 text-left text-xs font-semibold uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3">Fecha</th><th class="px-5 py-3">Venta</th><th class="px-5 py-3">Importe usado</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($referral->rewardUses as $rewardUse)<tr><td class="px-5 py-4 text-slate-600">{{ $rewardUse->created_at->format('d/m/Y') }}</td><td class="px-5 py-4"><a href="{{ route('sales.show', $rewardUse->sale) }}" class="font-medium text-indigo-700 hover:text-indigo-500">Venta #{{ $rewardUse->sale->id }}</a></td><td class="px-5 py-4 text-slate-800">Q{{ number_format((float) $rewardUse->amount, 2) }}</td></tr>@empty<tr><td colspan="3" class="px-5 py-8 text-center text-slate-500">El beneficio no se ha utilizado.</td></tr>@endforelse</tbody></table></div></section>
@endsection
