@extends('layouts.admin')

@section('title', $service->name)

@section('content')
    <div class="mb-6 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><a href="{{ route('services.index') }}" class="text-sm font-medium text-indigo-700 hover:text-indigo-500">← Volver a servicios</a><div class="mt-3 flex flex-wrap items-center gap-3"><h1 class="text-3xl font-bold tracking-tight">{{ $service->name }}</h1><x-status-badge :active="$service->is_active" /></div></div>@can('services.manage')<a href="{{ route('services.edit', $service) }}" class="rounded-lg bg-indigo-600 px-4 py-2.5 text-center text-sm font-semibold text-white hover:bg-indigo-500">Editar</a>@endcan</div>
    <div class="grid gap-5 lg:grid-cols-[2fr_1fr]"><section class="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-7"><h2 class="text-lg font-bold">Descripción</h2><p class="mt-3 whitespace-pre-line text-slate-700">{{ $service->description ?: 'Sin descripción registrada.' }}</p></section><aside class="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h2 class="text-lg font-bold">Sucursales relacionadas</h2><ul class="mt-4 grid gap-2">@forelse ($service->branches as $branch)<li><a href="{{ route('branches.show', $branch) }}" class="block rounded-lg bg-slate-50 px-3 py-2 text-sm font-medium text-indigo-700 hover:text-indigo-500">{{ $branch->name }}</a></li>@empty<li class="text-sm text-slate-500">No está asociado a sucursales.</li>@endforelse</ul></aside></div>
    @can('services.manage')<div class="mt-5 flex flex-wrap gap-3"><form method="POST" action="{{ route('services.toggle-status', $service) }}" onsubmit="return confirm('¿Deseas cambiar el estado de este servicio?');">@csrf @method('PATCH')<button class="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50">{{ $service->is_active ? 'Desactivar' : 'Activar' }}</button></form>@if ($service->is_active)<form method="POST" action="{{ route('services.destroy', $service) }}" onsubmit="return confirm('¿Deseas desactivar este servicio?');">@csrf @method('DELETE')<button class="rounded-lg border border-red-300 px-4 py-2.5 text-sm font-semibold text-red-700 hover:bg-red-50">Desactivar</button></form>@endif</div>@endcan
@endsection
