@extends('layouts.admin')

@section('title', 'Asignaciones de turno')

@section('content')
    <div class="mb-6 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-semibold uppercase tracking-widest text-indigo-600">Personal</p><h1 class="mt-1 text-3xl font-bold tracking-tight">Asignaciones de turno</h1><p class="mt-2 text-slate-600">Vigencias y dias de trabajo por empleado.</p></div><a href="{{ route('employee-shift-assignments.create') }}" class="rounded-lg bg-indigo-600 px-4 py-2.5 text-center text-sm font-semibold text-white hover:bg-indigo-500">Asignar turno</a></div>
    <form method="GET" class="mb-5 flex flex-col gap-3 rounded-xl bg-white p-4 shadow-sm ring-1 ring-slate-200 sm:flex-row sm:items-end"><div class="sm:w-96"><label for="employee_id" class="text-sm font-medium text-slate-700">Empleado</label><select id="employee_id" name="employee_id" class="mt-1 block w-full rounded-lg border-slate-300"><option value="">Todos los empleados</option>@foreach ($employees as $employee)<option value="{{ $employee->id }}" @selected($selectedEmployeeId === $employee->id)>{{ $employee->fullName() }} · {{ $employee->branch->name }}</option>@endforeach</select></div><div class="flex gap-2"><button type="submit" class="rounded-lg bg-slate-800 px-4 py-2.5 text-sm font-semibold text-white hover:bg-slate-700">Filtrar</button><a href="{{ route('employee-shift-assignments.index') }}" class="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50">Limpiar</a></div></form>
    <div class="overflow-hidden rounded-xl bg-white shadow-sm ring-1 ring-slate-200"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50 text-left text-xs font-semibold uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3">Empleado</th><th class="px-5 py-3">Turno</th><th class="px-5 py-3">Vigencia</th><th class="px-5 py-3">Dia</th><th class="px-5 py-3">Estado</th><th class="px-5 py-3"><span class="sr-only">Acciones</span></th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($assignments as $assignment)<tr><td class="px-5 py-4"><a href="{{ route('employees.show', $assignment->employee) }}" class="font-semibold text-indigo-700 hover:text-indigo-500">{{ $assignment->employee->fullName() }}</a><p class="mt-1 text-xs text-slate-500">{{ $assignment->employee->position->name }} · {{ $assignment->employee->branch->name }}</p></td><td class="px-5 py-4 text-slate-600">{{ $assignment->workShift->name }} · {{ substr($assignment->workShift->start_time, 0, 5) }}-{{ substr($assignment->workShift->end_time, 0, 5) }}</td><td class="px-5 py-4 text-slate-600">{{ $assignment->effective_from->format('d/m/Y') }} - {{ $assignment->effective_until?->format('d/m/Y') ?? 'Sin fin' }}</td><td class="px-5 py-4 text-slate-600">{{ $assignment->day_of_week ? ucfirst($assignment->day_of_week) : 'Todos' }}</td><td class="px-5 py-4"><x-status-badge :active="$assignment->is_active" /></td><td class="px-5 py-4 text-right"><a href="{{ route('employee-shift-assignments.edit', $assignment) }}" class="text-sm font-medium text-indigo-700 hover:text-indigo-500">Editar</a></td></tr>@empty<tr><td colspan="6" class="px-5 py-10 text-center text-slate-500">No hay asignaciones registradas.</td></tr>@endforelse</tbody></table></div>@if ($assignments->hasPages())<div class="border-t border-slate-200 px-5 py-4">{{ $assignments->links() }}</div>@endif</div>
@endsection
