@extends('layouts.admin')

@section('title', $inventoryItem ? 'Editar artículo' : 'Nuevo artículo')

@section('content')
    <div class="mb-6"><a href="{{ route('inventory-items.index') }}" class="text-sm font-medium text-indigo-700 hover:text-indigo-500">Volver a inventario</a><h1 class="mt-3 text-3xl font-bold tracking-tight">{{ $inventoryItem ? 'Editar artículo' : 'Nuevo artículo' }}</h1></div>

    <form method="POST" action="{{ $inventoryItem ? route('inventory-items.update', $inventoryItem) : route('inventory-items.store') }}" class="max-w-4xl rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-7">
        @csrf
        @if ($inventoryItem) @method('PUT') @endif
        <div class="grid gap-5 sm:grid-cols-2">
            <div><label for="branch_id" class="text-sm font-medium text-slate-700">Sucursal</label><select id="branch_id" name="branch_id" required class="mt-1 block w-full rounded-lg border-slate-300"><option value="">Selecciona una sucursal</option>@foreach ($branches as $branch)<option value="{{ $branch->id }}" @selected((int) old('branch_id', $inventoryItem?->branch_id) === $branch->id)>{{ $branch->name }}</option>@endforeach</select><x-field-error name="branch_id" /></div>
            <div><label for="type" class="text-sm font-medium text-slate-700">Tipo</label><select id="type" name="type" required class="mt-1 block w-full rounded-lg border-slate-300">@foreach ($types as $type)<option value="{{ $type->value }}" @selected(old('type', $inventoryItem?->type->value) === $type->value)>{{ $type->label() }}</option>@endforeach</select><x-field-error name="type" /></div>
            <div><label for="name" class="text-sm font-medium text-slate-700">Nombre</label><input id="name" name="name" value="{{ old('name', $inventoryItem?->name) }}" required class="mt-1 block w-full rounded-lg border-slate-300"><x-field-error name="name" /></div>
            <div><label for="internal_code" class="text-sm font-medium text-slate-700">Código interno / barcode</label><input id="internal_code" name="internal_code" value="{{ old('internal_code', $inventoryItem?->internal_code) }}" required class="mt-1 block w-full rounded-lg border-slate-300"><p class="mt-1 text-xs text-slate-500">Este identificador único queda listo para codificación de barras.</p><x-field-error name="internal_code" /></div>
            <div><label for="quantity" class="text-sm font-medium text-slate-700">Cantidad inicial</label><input id="quantity" name="quantity" type="number" min="0" value="{{ old('quantity', $inventoryItem?->quantity) }}" class="mt-1 block w-full rounded-lg border-slate-300"><p class="mt-1 text-xs text-slate-500">Déjala vacía si el artículo no maneja stock.</p><x-field-error name="quantity" /></div>
            <div><label for="minimum_stock" class="text-sm font-medium text-slate-700">Stock mínimo</label><input id="minimum_stock" name="minimum_stock" type="number" min="0" value="{{ old('minimum_stock', $inventoryItem?->minimum_stock) }}" class="mt-1 block w-full rounded-lg border-slate-300"><x-field-error name="minimum_stock" /></div>
            <div><label for="status" class="text-sm font-medium text-slate-700">Estado</label><select id="status" name="status" required class="mt-1 block w-full rounded-lg border-slate-300"><option value="active" @selected(old('status', $inventoryItem?->status->value ?? 'active') === 'active')>Activo</option><option value="maintenance" @selected(old('status', $inventoryItem?->status->value) === 'maintenance')>En mantenimiento</option><option value="inactive" @selected(old('status', $inventoryItem?->status->value) === 'inactive')>Inactivo</option></select><x-field-error name="status" /></div>
            <label class="flex items-center gap-2 self-end text-sm text-slate-700"><input type="hidden" name="maintenance_required" value="0"><input type="checkbox" name="maintenance_required" value="1" @checked(old('maintenance_required', $inventoryItem?->maintenance_required ?? false)) class="rounded border-slate-300 text-indigo-600">Requiere mantenimiento</label>
            <div class="sm:col-span-2"><label for="description" class="text-sm font-medium text-slate-700">Descripción <span class="text-slate-500">(obligatoria para equipos)</span></label><textarea id="description" name="description" rows="3" class="mt-1 block w-full rounded-lg border-slate-300">{{ old('description', $inventoryItem?->description) }}</textarea><x-field-error name="description" /></div>
            <div><label for="acquisition_date" class="text-sm font-medium text-slate-700">Fecha de adquisición</label><input id="acquisition_date" name="acquisition_date" type="date" value="{{ old('acquisition_date', $inventoryItem?->acquisition_date?->toDateString()) }}" class="mt-1 block w-full rounded-lg border-slate-300"><x-field-error name="acquisition_date" /></div>
            <div><label for="brand" class="text-sm font-medium text-slate-700">Marca</label><input id="brand" name="brand" value="{{ old('brand', $inventoryItem?->brand) }}" class="mt-1 block w-full rounded-lg border-slate-300"><x-field-error name="brand" /></div>
            <div><label for="model" class="text-sm font-medium text-slate-700">Modelo</label><input id="model" name="model" value="{{ old('model', $inventoryItem?->model) }}" class="mt-1 block w-full rounded-lg border-slate-300"><x-field-error name="model" /></div>
            <div><label for="serial" class="text-sm font-medium text-slate-700">Serie</label><input id="serial" name="serial" value="{{ old('serial', $inventoryItem?->serial) }}" class="mt-1 block w-full rounded-lg border-slate-300"><x-field-error name="serial" /></div>
            <div class="sm:col-span-2"><label for="notes" class="text-sm font-medium text-slate-700">Notas</label><textarea id="notes" name="notes" rows="3" class="mt-1 block w-full rounded-lg border-slate-300">{{ old('notes', $inventoryItem?->notes) }}</textarea><x-field-error name="notes" /></div>
        </div>
        <div class="mt-7 flex flex-wrap gap-3"><button type="submit" class="rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-indigo-500">{{ $inventoryItem ? 'Guardar cambios' : 'Crear artículo' }}</button><a href="{{ $inventoryItem ? route('inventory-items.show', $inventoryItem) : route('inventory-items.index') }}" class="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50">Cancelar</a></div>
    </form>
@endsection
