@extends('layouts.admin')

@section('title', 'Movimientos de inventario')

@section('content')
    <div class="mb-6"><a href="{{ route('inventory-items.show', $inventoryItem) }}" class="text-sm font-medium text-indigo-700 hover:text-indigo-500">Volver a {{ $inventoryItem->name }}</a><h1 class="mt-3 text-3xl font-bold tracking-tight">Movimientos de inventario</h1><p class="mt-2 text-slate-600">Stock actual: <span class="font-semibold text-slate-800">{{ $inventoryItem->quantity }}</span> · {{ $inventoryItem->internal_code }}</p></div>
    @can('register_inventory_movements')<section class="mb-5 max-w-3xl rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h2 class="text-lg font-semibold text-slate-800">Registrar movimiento</h2><form method="POST" action="{{ route('inventory-items.movements.store', $inventoryItem) }}" class="mt-4 grid gap-4 sm:grid-cols-3">@csrf <div><label for="type" class="text-sm font-medium text-slate-700">Tipo</label><select id="type" name="type" required class="mt-1 block w-full rounded-lg border-slate-300">@foreach ($movementTypes as $movementType)<option value="{{ $movementType->value }}" @selected(old('type') === $movementType->value)>{{ $movementType->label() }}</option>@endforeach</select><x-field-error name="type" /></div><div><label for="quantity" class="text-sm font-medium text-slate-700">Cantidad</label><input id="quantity" name="quantity" type="number" min="0" value="{{ old('quantity') }}" required class="mt-1 block w-full rounded-lg border-slate-300"><x-field-error name="quantity" /></div><div><label for="reason" class="text-sm font-medium text-slate-700">Motivo</label><input id="reason" name="reason" value="{{ old('reason') }}" class="mt-1 block w-full rounded-lg border-slate-300"><x-field-error name="reason" /></div><p class="text-xs text-slate-500 sm:col-span-2">El ajuste establece la existencia final; las entradas y salidas usan la cantidad indicada.</p><div class="flex items-end"><button type="submit" class="w-full rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-indigo-500">Guardar movimiento</button></div></form></section>@endcan
    <div class="overflow-hidden rounded-xl bg-white shadow-sm ring-1 ring-slate-200"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50 text-left text-xs font-semibold uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3">Fecha</th><th class="px-5 py-3">Tipo</th><th class="px-5 py-3">Cantidad</th><th class="px-5 py-3">Motivo</th><th class="px-5 py-3">Usuario</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($movements as $movement)<tr><td class="px-5 py-4 text-slate-600">{{ $movement->created_at->format('d/m/Y H:i') }}</td><td class="px-5 py-4 font-medium text-slate-800">{{ $movement->type->label() }}</td><td class="px-5 py-4 text-slate-700">{{ $movement->quantity }}</td><td class="px-5 py-4 text-slate-600">{{ $movement->reason ?: '—' }}</td><td class="px-5 py-4 text-slate-600">{{ $movement->user->name }}</td></tr>@empty<tr><td colspan="5" class="px-5 py-10 text-center text-slate-500">No hay movimientos registrados.</td></tr>@endforelse</tbody></table></div>@if ($movements->hasPages())<div class="border-t border-slate-200 px-5 py-4">{{ $movements->links() }}</div>@endif</div>
@endsection
