@extends('layouts.admin')

@section('title', $client->first_name.' '.$client->last_name)

@section('content')
    @php($currentMembership = $client->memberships->firstWhere('status', \App\ClientMembershipStatus::Active))
    <div class="mb-6 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><a href="{{ route('clients.index') }}" class="text-sm font-medium text-indigo-700 hover:text-indigo-500">← Volver a clientes</a><div class="mt-3 flex flex-wrap items-center gap-3"><h1 class="text-3xl font-bold tracking-tight">{{ $client->first_name }} {{ $client->last_name }}</h1><x-status-badge :active="$client->is_active" /></div><p class="mt-2 font-mono text-sm text-slate-500">{{ $client->code }}</p></div><div class="flex flex-wrap gap-2">@can('client-memberships.manage')<a href="{{ route('client-memberships.create', ['client_id' => $client->id]) }}" class="rounded-lg border border-indigo-600 px-4 py-2.5 text-center text-sm font-semibold text-indigo-700 hover:bg-indigo-50">Asignar membresía</a>@endcan @can('clients.manage')<a href="{{ route('clients.edit', $client) }}" class="rounded-lg bg-indigo-600 px-4 py-2.5 text-center text-sm font-semibold text-white hover:bg-indigo-500">Editar</a>@endcan</div></div>
    <div class="grid gap-5 lg:grid-cols-[2fr_1fr]"><section class="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-7"><h2 class="text-lg font-bold">Información del cliente</h2><dl class="mt-5 grid gap-5 sm:grid-cols-2"><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Sucursal</dt><dd class="mt-1 text-slate-800">{{ $client->branch->name }}</dd></div><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Fecha de inscripción</dt><dd class="mt-1 text-slate-800">{{ $client->registration_date->format('d/m/Y') }}</dd></div><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Nacimiento</dt><dd class="mt-1 text-slate-800">{{ $client->birth_date?->format('d/m/Y') ?? 'No registrada' }}</dd></div><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Contacto</dt><dd class="mt-1 text-slate-800">{{ $client->phone ?: 'Sin teléfono' }}<br>{{ $client->email ?: 'Sin correo' }}</dd></div><div class="sm:col-span-2"><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Dirección</dt><dd class="mt-1 text-slate-800">{{ $client->address ?: 'No registrada' }}</dd></div></dl></section><aside class="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h2 class="text-lg font-bold">Membresía actual</h2>@if ($currentMembership)<p class="mt-3 font-semibold text-slate-800">{{ $currentMembership->membershipType->name }}</p><p class="mt-1 text-sm text-slate-600">Vence: {{ $currentMembership->end_date->format('d/m/Y') }}</p>@else<p class="mt-3 text-sm text-slate-500">No tiene una membresía activa.</p>@endif</aside></div>
    <section class="mt-5 overflow-hidden rounded-xl bg-white shadow-sm ring-1 ring-slate-200"><div class="border-b border-slate-200 px-5 py-4"><h2 class="text-lg font-bold">Historial de membresías</h2></div><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50 text-left text-xs font-semibold uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3">Tipo</th><th class="px-5 py-3">Período</th><th class="px-5 py-3">Precio aplicado</th><th class="px-5 py-3">Estado</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($client->memberships as $membership)<tr><td class="px-5 py-4"><a href="{{ route('client-memberships.show', $membership) }}" class="font-medium text-indigo-700 hover:text-indigo-500">{{ $membership->membershipType->name }}</a></td><td class="px-5 py-4 text-slate-600">{{ $membership->start_date->format('d/m/Y') }} – {{ $membership->end_date->format('d/m/Y') }}</td><td class="px-5 py-4 text-slate-600">{{ number_format((float) $membership->applied_price, 2) }}</td><td class="px-5 py-4"><x-status-badge :active="$membership->status === \App\ClientMembershipStatus::Active" :active-label="$membership->status->value" :inactive-label="$membership->status->value" /></td></tr>@empty<tr><td colspan="4" class="px-5 py-8 text-center text-slate-500">No hay membresías registradas.</td></tr>@endforelse</tbody></table></div></section>
    @can('clients.manage')<div class="mt-5 flex flex-wrap gap-3"><form method="POST" action="{{ route('clients.toggle-status', $client) }}" onsubmit="return confirm('¿Deseas cambiar el estado de este cliente?');">@csrf @method('PATCH')<button class="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50">{{ $client->is_active ? 'Desactivar' : 'Activar' }}</button></form>@if ($client->is_active)<form method="POST" action="{{ route('clients.destroy', $client) }}" onsubmit="return confirm('¿Deseas desactivar este cliente?');">@csrf @method('DELETE')<button class="rounded-lg border border-red-300 px-4 py-2.5 text-sm font-semibold text-red-700 hover:bg-red-50">Desactivar</button></form>@endif</div>@endcan
    <section class="mt-5 grid gap-5 xl:grid-cols-2">
        <div class="overflow-hidden rounded-xl bg-white shadow-sm ring-1 ring-slate-200">
            <div class="flex items-center justify-between border-b border-slate-200 px-5 py-4"><h2 class="text-lg font-bold">Historial de pagos</h2>@can('payments.manage')<a href="{{ route('payments.create', ['client_id' => $client->id]) }}" class="text-sm font-medium text-indigo-700 hover:text-indigo-500">Registrar pago</a>@endcan</div>
            <div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50 text-left text-xs font-semibold uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3">Fecha</th><th class="px-5 py-3">Monto</th><th class="px-5 py-3">Origen</th><th class="px-5 py-3"><span class="sr-only">Ver</span></th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($client->payments as $payment)<tr><td class="px-5 py-4 text-slate-600">{{ $payment->payment_date->format('d/m/Y') }}</td><td class="px-5 py-4 text-slate-800">{{ number_format((float) $payment->amount, 2) }}</td><td class="px-5 py-4 text-slate-600">{{ $payment->sale ? 'Venta' : ($payment->clientMembership ? 'Renovación' : 'Manual') }}</td><td class="px-5 py-4 text-right"><a href="{{ route('payments.show', $payment) }}" class="text-sm font-medium text-indigo-700 hover:text-indigo-500">Ver</a></td></tr>@empty<tr><td colspan="4" class="px-5 py-8 text-center text-slate-500">No hay pagos registrados.</td></tr>@endforelse</tbody></table></div>
        </div>
        <div class="overflow-hidden rounded-xl bg-white shadow-sm ring-1 ring-slate-200">
            <div class="flex items-center justify-between border-b border-slate-200 px-5 py-4"><h2 class="text-lg font-bold">Historial de ventas</h2>@can('sales.manage')<a href="{{ route('sales.create', ['client_id' => $client->id]) }}" class="text-sm font-medium text-indigo-700 hover:text-indigo-500">Registrar venta</a>@endcan</div>
            <div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50 text-left text-xs font-semibold uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3">Fecha</th><th class="px-5 py-3">Sucursal</th><th class="px-5 py-3">Total</th><th class="px-5 py-3"><span class="sr-only">Ver</span></th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($client->sales as $sale)<tr><td class="px-5 py-4 text-slate-600">{{ $sale->sale_date->format('d/m/Y') }}</td><td class="px-5 py-4 text-slate-600">{{ $sale->branch->name }}</td><td class="px-5 py-4 text-slate-800">{{ number_format((float) $sale->total, 2) }}</td><td class="px-5 py-4 text-right"><a href="{{ route('sales.show', $sale) }}" class="text-sm font-medium text-indigo-700 hover:text-indigo-500">Ver</a></td></tr>@empty<tr><td colspan="4" class="px-5 py-8 text-center text-slate-500">No hay ventas registradas.</td></tr>@endforelse</tbody></table></div>
        </div>
    </section>
    <section class="mt-5 overflow-hidden rounded-xl bg-white shadow-sm ring-1 ring-slate-200"><div class="flex items-center justify-between border-b border-slate-200 px-5 py-4"><h2 class="text-lg font-bold">Historial de actividades</h2>@can('enrollments.register')<a href="{{ route('class-enrollments.create', ['client_id' => $client->id]) }}" class="text-sm font-medium text-indigo-700 hover:text-indigo-500">Inscribir en actividad</a>@endcan</div><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50 text-left text-xs font-semibold uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3">Clase</th><th class="px-5 py-3">Sucursal</th><th class="px-5 py-3">Fecha</th><th class="px-5 py-3">Horario</th><th class="px-5 py-3">Estado</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($client->gymClassEnrollments as $enrollment)<tr><td class="px-5 py-4"><a href="{{ route('gym-classes.show', $enrollment->gymClassSchedule->gymClass) }}" class="font-medium text-indigo-700 hover:text-indigo-500">{{ $enrollment->gymClassSchedule->gymClass->name }}</a></td><td class="px-5 py-4 text-slate-600">{{ $enrollment->gymClassSchedule->gymClass->branch->name }}</td><td class="px-5 py-4 text-slate-600">{{ $enrollment->enrollment_date->format('d/m/Y') }}</td><td class="px-5 py-4 text-slate-600">{{ substr($enrollment->gymClassSchedule->start_time, 0, 5) }}</td><td class="px-5 py-4"><span class="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-700">{{ ucfirst($enrollment->status->value) }}</span></td></tr>@empty<tr><td colspan="5" class="px-5 py-8 text-center text-slate-500">No hay actividades registradas.</td></tr>@endforelse</tbody></table></div></section>
    @can('referrals.view')
        <section class="mt-5 grid gap-5 lg:grid-cols-[2fr_1fr]">
            <div class="overflow-hidden rounded-xl bg-white shadow-sm ring-1 ring-slate-200"><div class="border-b border-slate-200 px-5 py-4"><h2 class="text-lg font-bold">Referidos</h2></div><div class="p-5"><p class="text-sm text-slate-600">Referidor: @if ($client->referralReceived)<a href="{{ route('clients.show', $client->referralReceived->referrer) }}" class="font-medium text-indigo-700 hover:text-indigo-500">{{ $client->referralReceived->referrer->first_name }} {{ $client->referralReceived->referrer->last_name }}</a>@else Sin referidor registrado.@endif</p><ul class="mt-4 grid gap-2">@forelse ($client->referralsSent as $referral)<li class="rounded-lg bg-slate-50 px-3 py-2 text-sm"><a href="{{ route('referrals.show', $referral) }}" class="font-medium text-indigo-700 hover:text-indigo-500">{{ $referral->referred->first_name }} {{ $referral->referred->last_name }}</a><span class="ml-2 text-slate-500">{{ $referral->status->value }} · {{ $referral->reward_status->value }}</span></li>@empty<li class="text-sm text-slate-500">No ha generado referidos.</li>@endforelse</ul></div></div>
            <aside class="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h2 class="text-lg font-bold">Saldo de referidos</h2><dl class="mt-4 space-y-3 text-sm"><div class="flex justify-between gap-4"><dt class="text-slate-600">Disponible</dt><dd class="font-semibold text-emerald-700">Q{{ number_format((float) $referralSummary['available_reward_amount'], 2) }}</dd></div><div class="flex justify-between gap-4"><dt class="text-slate-600">Usado</dt><dd class="font-semibold text-slate-800">Q{{ number_format((float) $referralSummary['used_reward_amount'], 2) }}</dd></div></dl></aside>
        </section>
    @endcan
@endsection
