@extends('layouts.admin')

@section('title', $client->first_name.' '.$client->last_name)

@section('content')
    @php($currentMembership = $client->memberships->firstWhere('status', \App\ClientMembershipStatus::Active))
    <div class="mb-6 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><a href="{{ route('clients.index') }}" class="text-sm font-medium text-indigo-700 hover:text-indigo-500">← Volver a clientes</a><div class="mt-3 flex flex-wrap items-center gap-3"><h1 class="text-3xl font-bold tracking-tight">{{ $client->first_name }} {{ $client->last_name }}</h1><x-status-badge :active="$client->is_active" /></div><p class="mt-2 font-mono text-sm text-slate-500">{{ $client->code }}</p></div><div class="flex flex-wrap gap-2">@can('client-memberships.manage')<a href="{{ route('client-memberships.create', ['client_id' => $client->id]) }}" class="rounded-lg border border-indigo-600 px-4 py-2.5 text-center text-sm font-semibold text-indigo-700 hover:bg-indigo-50">Asignar membresía</a>@endcan @can('clients.manage')<a href="{{ route('clients.edit', $client) }}" class="rounded-lg bg-indigo-600 px-4 py-2.5 text-center text-sm font-semibold text-white hover:bg-indigo-500">Editar</a>@endcan</div></div>
    <div class="grid gap-5 lg:grid-cols-[2fr_1fr]"><section class="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-7"><h2 class="text-lg font-bold">Información del cliente</h2><dl class="mt-5 grid gap-5 sm:grid-cols-2"><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Sucursal</dt><dd class="mt-1 text-slate-800">{{ $client->branch->name }}</dd></div><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Fecha de inscripción</dt><dd class="mt-1 text-slate-800">{{ $client->registration_date->format('d/m/Y') }}</dd></div><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Nacimiento</dt><dd class="mt-1 text-slate-800">{{ $client->birth_date?->format('d/m/Y') ?? 'No registrada' }}</dd></div><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Contacto</dt><dd class="mt-1 text-slate-800">{{ $client->phone ?: 'Sin teléfono' }}<br>{{ $client->email ?: 'Sin correo' }}</dd></div><div class="sm:col-span-2"><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Dirección</dt><dd class="mt-1 text-slate-800">{{ $client->address ?: 'No registrada' }}</dd></div></dl></section><aside class="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h2 class="text-lg font-bold">Membresía actual</h2>@if ($currentMembership)<p class="mt-3 font-semibold text-slate-800">{{ $currentMembership->membershipType->name }}</p><p class="mt-1 text-sm text-slate-600">Vence: {{ $currentMembership->end_date->format('d/m/Y') }}</p>@else<p class="mt-3 text-sm text-slate-500">No tiene una membresía activa.</p>@endif</aside></div>
    <section class="mt-5 overflow-hidden rounded-xl bg-white shadow-sm ring-1 ring-slate-200"><div class="border-b border-slate-200 px-5 py-4"><h2 class="text-lg font-bold">Historial de membresías</h2></div><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50 text-left text-xs font-semibold uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3">Tipo</th><th class="px-5 py-3">Período</th><th class="px-5 py-3">Precio aplicado</th><th class="px-5 py-3">Estado</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($client->memberships as $membership)<tr><td class="px-5 py-4"><a href="{{ route('client-memberships.show', $membership) }}" class="font-medium text-indigo-700 hover:text-indigo-500">{{ $membership->membershipType->name }}</a></td><td class="px-5 py-4 text-slate-600">{{ $membership->start_date->format('d/m/Y') }} – {{ $membership->end_date->format('d/m/Y') }}</td><td class="px-5 py-4 text-slate-600">{{ number_format((float) $membership->applied_price, 2) }}</td><td class="px-5 py-4"><x-status-badge :active="$membership->status === \App\ClientMembershipStatus::Active" :active-label="$membership->status->value" :inactive-label="$membership->status->value" /></td></tr>@empty<tr><td colspan="4" class="px-5 py-8 text-center text-slate-500">No hay membresías registradas.</td></tr>@endforelse</tbody></table></div></section>
    @can('clients.manage')<div class="mt-5 flex flex-wrap gap-3"><form method="POST" action="{{ route('clients.toggle-status', $client) }}" onsubmit="return confirm('¿Deseas cambiar el estado de este cliente?');">@csrf @method('PATCH')<button class="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50">{{ $client->is_active ? 'Desactivar' : 'Activar' }}</button></form>@if ($client->is_active)<form method="POST" action="{{ route('clients.destroy', $client) }}" onsubmit="return confirm('¿Deseas desactivar este cliente?');">@csrf @method('DELETE')<button class="rounded-lg border border-red-300 px-4 py-2.5 text-sm font-semibold text-red-700 hover:bg-red-50">Desactivar</button></form>@endif</div>@endcan
@endsection
