@extends('layouts.admin')

@section('title', $thirdPartyItem ? 'Editar articulo externo' : 'Nuevo articulo externo')

@section('content')
    @php($selectedBranchIds = array_map('intval', old('branch_ids', $selectedBranchIds)))
    <div class="mb-6"><a href="{{ route('third-party-items.index') }}" class="text-sm font-medium text-indigo-700 hover:text-indigo-500">Volver a productos externos</a><h1 class="mt-3 text-3xl font-bold tracking-tight">{{ $thirdPartyItem ? 'Editar articulo externo' : 'Nuevo articulo externo' }}</h1></div>
    <form method="POST" action="{{ $thirdPartyItem ? route('third-party-items.update', $thirdPartyItem) : route('third-party-items.store') }}" class="max-w-4xl rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-7">@csrf @if ($thirdPartyItem) @method('PUT') @endif
        <div class="grid gap-5 sm:grid-cols-2"><div><label for="third_party_id" class="text-sm font-medium text-slate-700">Tercero comercial</label><select id="third_party_id" name="third_party_id" required class="mt-1 block w-full rounded-lg border-slate-300"><option value="">Selecciona un tercero</option>@foreach ($commercialPartners as $commercialPartner)<option value="{{ $commercialPartner->id }}" @selected((int) old('third_party_id', $thirdPartyItem?->third_party_id) === $commercialPartner->id)>{{ $commercialPartner->name }}</option>@endforeach</select><x-field-error name="third_party_id" /></div><div><label for="type" class="text-sm font-medium text-slate-700">Tipo</label><select id="type" name="type" required class="mt-1 block w-full rounded-lg border-slate-300"><option value="product" @selected(old('type', $thirdPartyItem?->type->value) === 'product')>Producto</option><option value="service" @selected(old('type', $thirdPartyItem?->type->value) === 'service')>Servicio</option></select><x-field-error name="type" /></div><div><label for="name" class="text-sm font-medium text-slate-700">Nombre</label><input id="name" name="name" value="{{ old('name', $thirdPartyItem?->name) }}" required class="mt-1 block w-full rounded-lg border-slate-300"><x-field-error name="name" /></div><div><label for="base_price" class="text-sm font-medium text-slate-700">Precio base</label><input id="base_price" name="base_price" type="number" min="0" step="0.01" value="{{ old('base_price', $thirdPartyItem?->base_price) }}" required class="mt-1 block w-full rounded-lg border-slate-300"><x-field-error name="base_price" /></div><div class="sm:col-span-2"><label for="description" class="text-sm font-medium text-slate-700">Descripcion</label><textarea id="description" name="description" rows="4" class="mt-1 block w-full rounded-lg border-slate-300">{{ old('description', $thirdPartyItem?->description) }}</textarea><x-field-error name="description" /></div><fieldset class="sm:col-span-2"><legend class="text-sm font-medium text-slate-700">Sucursales disponibles</legend><p class="mt-1 text-sm text-slate-500">El articulo solo podra venderse en las sucursales seleccionadas.</p><div class="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">@foreach ($branches as $branch)<label class="flex items-center gap-2 rounded-lg border border-slate-200 p-3 text-sm"><input type="checkbox" name="branch_ids[]" value="{{ $branch->id }}" @checked(in_array($branch->id, $selectedBranchIds, true)) class="rounded border-slate-300 text-indigo-600">{{ $branch->name }}</label>@endforeach</div><x-field-error name="branch_ids" /></fieldset><label class="flex items-center gap-2 text-sm text-slate-700 sm:col-span-2"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $thirdPartyItem?->is_active ?? true)) class="rounded border-slate-300 text-indigo-600">Articulo activo</label></div>
        <div class="mt-7 flex flex-wrap gap-3"><button type="submit" class="rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-indigo-500">{{ $thirdPartyItem ? 'Guardar cambios' : 'Crear articulo' }}</button><a href="{{ $thirdPartyItem ? route('third-party-items.show', $thirdPartyItem) : route('third-party-items.index') }}" class="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50">Cancelar</a></div>
    </form>
@endsection
