@extends('layouts.admin')

@section('title', $thirdPartyItem->name)

@section('content')
    <div class="mb-6 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><a href="{{ route('third-party-items.index') }}" class="text-sm font-medium text-indigo-700 hover:text-indigo-500">Volver a productos externos</a><div class="mt-3 flex flex-wrap items-center gap-3"><h1 class="text-3xl font-bold tracking-tight">{{ $thirdPartyItem->name }}</h1><x-status-badge :active="$thirdPartyItem->is_active" /></div></div>@can('third-party-items.manage')<a href="{{ route('third-party-items.edit', $thirdPartyItem) }}" class="rounded-lg bg-indigo-600 px-4 py-2.5 text-center text-sm font-semibold text-white hover:bg-indigo-500">Editar</a>@endcan</div>
    <div class="grid gap-5 lg:grid-cols-[2fr_1fr]"><section class="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-7"><h2 class="text-lg font-bold">Detalle del articulo</h2><dl class="mt-5 grid gap-5 sm:grid-cols-2"><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Tercero</dt><dd class="mt-1"><a href="{{ route('commercial-partners.show', $thirdPartyItem->commercialPartner) }}" class="font-medium text-indigo-700 hover:text-indigo-500">{{ $thirdPartyItem->commercialPartner->name }}</a></dd></div><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Tipo</dt><dd class="mt-1 text-slate-800">{{ ucfirst($thirdPartyItem->type->value) }}</dd></div><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Precio base</dt><dd class="mt-1 text-slate-800">{{ number_format((float) $thirdPartyItem->base_price, 2) }}</dd></div><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Sucursales</dt><dd class="mt-1 text-slate-800">{{ $thirdPartyItem->branches->pluck('name')->join(', ') }}</dd></div><div class="sm:col-span-2"><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Descripcion</dt><dd class="mt-1 whitespace-pre-line text-slate-800">{{ $thirdPartyItem->description ?: 'Sin descripcion registrada.' }}</dd></div></dl></section><aside class="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h2 class="text-lg font-bold">Descuentos asociados</h2><ul class="mt-4 grid gap-2">@forelse ($thirdPartyItem->discounts as $discount)<li><a href="{{ route('discounts.show', $discount) }}" class="block rounded-lg bg-slate-50 px-3 py-2 text-sm font-medium text-indigo-700 hover:text-indigo-500">{{ $discount->name }}<span class="block pt-1 text-xs font-normal text-slate-500">{{ number_format((float) $discount->value, 2) }} · {{ $discount->type->value === 'percentage' ? '%' : 'monto fijo' }}</span></a></li>@empty<li class="text-sm text-slate-500">No hay descuentos asociados.</li>@endforelse</ul></aside></div>
    @can('third-party-items.manage')@if ($thirdPartyItem->is_active)<form method="POST" action="{{ route('third-party-items.destroy', $thirdPartyItem) }}" class="mt-5" onsubmit="return confirm('Deseas desactivar este articulo?');">@csrf @method('DELETE')<button class="rounded-lg border border-red-300 px-4 py-2.5 text-sm font-semibold text-red-700 hover:bg-red-50">Desactivar</button></form>@endif@endcan
@endsection
