@extends('layouts.admin')

@section('title', 'Registrar renovación')

@section('content')
    <div class="mb-6"><a href="{{ route('renewals.index') }}" class="text-sm font-medium text-indigo-700 hover:text-indigo-500">← Volver a renovaciones</a><h1 class="mt-3 text-3xl font-bold tracking-tight">Registrar renovación</h1><p class="mt-2 text-slate-600">Las fechas se registran de forma explícita; el sistema no inventa períodos ni duraciones.</p></div>
    <form method="POST" action="{{ route('renewals.store') }}" class="max-w-4xl rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-7">
        @csrf
        <div class="grid gap-5 sm:grid-cols-2">
            <div><label for="client_id" class="text-sm font-medium text-slate-700">Cliente</label><select id="client_id" name="client_id" required class="mt-1 block w-full rounded-lg border-slate-300"><option value="">Selecciona un cliente</option>@foreach ($clients as $client)<option value="{{ $client->id }}" @selected((int) old('client_id', request('client_id')) === $client->id)>{{ $client->last_name }}, {{ $client->first_name }} · {{ $client->code }}</option>@endforeach</select><x-field-error name="client_id" /></div>
            <div><label for="membership_type_id" class="text-sm font-medium text-slate-700">Tipo de membresía</label><select id="membership_type_id" name="membership_type_id" required class="mt-1 block w-full rounded-lg border-slate-300"><option value="">Selecciona un tipo</option>@foreach ($membershipTypes as $membershipType)<option value="{{ $membershipType->id }}" @selected((int) old('membership_type_id') === $membershipType->id)>{{ $membershipType->name }} · {{ number_format((float) $membershipType->reference_price, 2) }}</option>@endforeach</select><x-field-error name="membership_type_id" /></div>
            <div><label for="start_date" class="text-sm font-medium text-slate-700">Fecha de inicio</label><input id="start_date" name="start_date" type="date" value="{{ old('start_date', now()->toDateString()) }}" required class="mt-1 block w-full rounded-lg border-slate-300"><x-field-error name="start_date" /></div>
            <div><label for="end_date" class="text-sm font-medium text-slate-700">Fecha de vencimiento</label><input id="end_date" name="end_date" type="date" value="{{ old('end_date') }}" required class="mt-1 block w-full rounded-lg border-slate-300"><x-field-error name="end_date" /></div>
            <div><label for="payment_date" class="text-sm font-medium text-slate-700">Fecha de pago</label><input id="payment_date" name="payment_date" type="date" value="{{ old('payment_date', now()->toDateString()) }}" required class="mt-1 block w-full rounded-lg border-slate-300"><x-field-error name="payment_date" /></div>
            <div><label for="amount" class="text-sm font-medium text-slate-700">Monto pagado</label><input id="amount" name="amount" type="number" min="0.01" step="0.01" value="{{ old('amount') }}" required class="mt-1 block w-full rounded-lg border-slate-300"><x-field-error name="amount" /></div>
            <div><label for="payment_method" class="text-sm font-medium text-slate-700">Método de pago</label><select id="payment_method" name="payment_method" required class="mt-1 block w-full rounded-lg border-slate-300">@foreach ($methods as $method)<option value="{{ $method->value }}" @selected(old('payment_method', 'cash') === $method->value)>{{ ucfirst($method->value) }}</option>@endforeach</select><x-field-error name="payment_method" /></div>
            <div><label for="reference" class="text-sm font-medium text-slate-700">Referencia de pago</label><input id="reference" name="reference" type="text" value="{{ old('reference') }}" class="mt-1 block w-full rounded-lg border-slate-300"><x-field-error name="reference" /></div>
            <div class="sm:col-span-2"><label for="observations" class="text-sm font-medium text-slate-700">Observaciones de la membresía</label><textarea id="observations" name="observations" rows="3" class="mt-1 block w-full rounded-lg border-slate-300">{{ old('observations') }}</textarea><x-field-error name="observations" /></div>
            <div class="sm:col-span-2"><label for="payment_observations" class="text-sm font-medium text-slate-700">Observaciones del pago</label><textarea id="payment_observations" name="payment_observations" rows="3" class="mt-1 block w-full rounded-lg border-slate-300">{{ old('payment_observations') }}</textarea><x-field-error name="payment_observations" /></div>
        </div>
        <div class="mt-7 flex flex-wrap gap-3"><button type="submit" class="rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-indigo-500">Registrar renovación y pago</button><a href="{{ route('renewals.index') }}" class="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50">Cancelar</a></div>
    </form>
@endsection
