@extends('layouts.admin')

@section('title', 'Asistencia laboral')

@section('content')
    <div class="mb-6 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-semibold uppercase tracking-widest text-indigo-600">Personal</p><h1 class="mt-1 text-3xl font-bold tracking-tight">Asistencia laboral</h1><p class="mt-2 text-slate-600">Entradas, salidas e historial de horas trabajadas.</p></div>@can('employee-attendances.register')<a href="{{ route('employee-attendances.create') }}" class="rounded-lg bg-indigo-600 px-4 py-2.5 text-center text-sm font-semibold text-white hover:bg-indigo-500">Registrar entrada</a>@endcan</div>
    <form method="GET" class="mb-5 grid gap-3 rounded-xl bg-white p-4 shadow-sm ring-1 ring-slate-200 sm:grid-cols-2 lg:grid-cols-5">
        <div><label for="employee_id" class="text-sm font-medium text-slate-700">Empleado</label><select id="employee_id" name="employee_id" class="mt-1 block w-full rounded-lg border-slate-300"><option value="">Todos</option>@foreach ($employees as $employee)<option value="{{ $employee->id }}" @selected((int) ($filters['employee_id'] ?? 0) === $employee->id)>{{ $employee->fullName() }}</option>@endforeach</select></div>
        <div><label for="branch_id" class="text-sm font-medium text-slate-700">Sucursal</label><select id="branch_id" name="branch_id" class="mt-1 block w-full rounded-lg border-slate-300"><option value="">Todas</option>@foreach ($branches as $branch)<option value="{{ $branch->id }}" @selected((int) ($filters['branch_id'] ?? 0) === $branch->id)>{{ $branch->name }}</option>@endforeach</select></div>
        <div><label for="attendance_date" class="text-sm font-medium text-slate-700">Fecha</label><input id="attendance_date" name="attendance_date" type="date" value="{{ $filters['attendance_date'] ?? '' }}" class="mt-1 block w-full rounded-lg border-slate-300"></div>
        <div><label for="status" class="text-sm font-medium text-slate-700">Estado</label><select id="status" name="status" class="mt-1 block w-full rounded-lg border-slate-300"><option value="">Todos</option>@foreach (\App\EmployeeAttendanceStatus::cases() as $status)<option value="{{ $status->value }}" @selected(($filters['status'] ?? null) === $status->value)>{{ ucfirst($status->value) }}</option>@endforeach</select></div>
        <div class="flex items-end gap-2"><button type="submit" class="rounded-lg bg-slate-800 px-4 py-2.5 text-sm font-semibold text-white hover:bg-slate-700">Filtrar</button><a href="{{ route('employee-attendances.index') }}" class="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50">Limpiar</a></div>
    </form>
    <div class="overflow-hidden rounded-xl bg-white shadow-sm ring-1 ring-slate-200"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50 text-left text-xs font-semibold uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3">Empleado</th><th class="px-5 py-3">Sucursal</th><th class="px-5 py-3">Fecha</th><th class="px-5 py-3">Turno</th><th class="px-5 py-3">Entrada</th><th class="px-5 py-3">Salida</th><th class="px-5 py-3">Duracion</th><th class="px-5 py-3">Estado</th><th class="px-5 py-3"><span class="sr-only">Acciones</span></th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($attendances as $attendance)<tr><td class="px-5 py-4"><a href="{{ route('employees.show', $attendance->employee) }}" class="font-semibold text-indigo-700 hover:text-indigo-500">{{ $attendance->employee->fullName() }}</a><p class="mt-1 text-xs text-slate-500">{{ $attendance->employee->position->name }}</p></td><td class="px-5 py-4 text-slate-600">{{ $attendance->branch->name }}</td><td class="px-5 py-4 text-slate-600">{{ $attendance->attendance_date->format('d/m/Y') }}</td><td class="px-5 py-4 text-slate-600">{{ $attendance->workShift?->name ?? 'Sin turno' }}</td><td class="px-5 py-4 text-slate-600">{{ substr($attendance->entry_time, 0, 5) }}</td><td class="px-5 py-4 text-slate-600">{{ $attendance->exit_time ? substr($attendance->exit_time, 0, 5) : 'Pendiente' }}</td><td class="px-5 py-4 text-slate-800">{{ $attendance->workedDuration() ?? 'Pendiente' }}</td><td class="px-5 py-4"><span class="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-700">{{ ucfirst($attendance->status->value) }}</span></td><td class="px-5 py-4 text-right"><a href="{{ route('employee-attendances.show', $attendance) }}" class="text-sm font-medium text-indigo-700 hover:text-indigo-500">Ver</a></td></tr>@empty<tr><td colspan="9" class="px-5 py-10 text-center text-slate-500">No hay asistencias registradas.</td></tr>@endforelse</tbody></table></div>@if ($attendances->hasPages())<div class="border-t border-slate-200 px-5 py-4">{{ $attendances->links() }}</div>@endif</div>
@endsection
