@extends('layouts.admin')

@section('title', 'Asistencia de '.$attendance->employee->fullName())

@section('content')
    <div class="mb-6 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><a href="{{ route('employee-attendances.index') }}" class="text-sm font-medium text-indigo-700 hover:text-indigo-500">Volver al historial</a><h1 class="mt-3 text-3xl font-bold tracking-tight">{{ $attendance->employee->fullName() }}</h1><p class="mt-2 text-slate-600">Asistencia del {{ $attendance->attendance_date->format('d/m/Y') }}</p></div><span class="rounded-full bg-slate-100 px-3 py-1.5 text-sm font-semibold text-slate-700">{{ ucfirst($attendance->status->value) }}</span></div>
    <div class="grid gap-5 lg:grid-cols-[2fr_1fr]"><section class="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-7"><h2 class="text-lg font-bold">Registro laboral</h2><dl class="mt-5 grid gap-5 sm:grid-cols-2"><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Sucursal</dt><dd class="mt-1 text-slate-800">{{ $attendance->branch->name }}</dd></div><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Puesto</dt><dd class="mt-1 text-slate-800">{{ $attendance->employee->position->name }}</dd></div><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Turno</dt><dd class="mt-1 text-slate-800">{{ $attendance->workShift?->name ?? 'Sin turno asignado' }}</dd></div><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Metodo</dt><dd class="mt-1 text-slate-800">{{ ucfirst($attendance->registration_method->value) }}</dd></div><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Entrada</dt><dd class="mt-1 text-slate-800">{{ substr($attendance->entry_time, 0, 5) }}</dd></div><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Salida</dt><dd class="mt-1 text-slate-800">{{ $attendance->exit_time ? substr($attendance->exit_time, 0, 5) : 'Pendiente' }}</dd></div><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Horas trabajadas</dt><dd class="mt-1 text-slate-800">{{ $attendance->workedDuration() ?? 'Pendiente de salida' }}</dd></div><div class="sm:col-span-2"><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Observaciones</dt><dd class="mt-1 whitespace-pre-line text-slate-800">{{ $attendance->observations ?: 'Sin observaciones.' }}</dd></div></dl></section><aside class="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h2 class="text-lg font-bold">Empleado</h2><p class="mt-3 font-semibold text-slate-800">{{ $attendance->employee->fullName() }}</p><p class="mt-1 text-sm text-slate-600">{{ $attendance->employee->code }}</p><a href="{{ route('employees.show', $attendance->employee) }}" class="mt-4 inline-block text-sm font-medium text-indigo-700 hover:text-indigo-500">Ver ficha del empleado</a></aside></div>
    @if ($attendance->exit_time === null)@can('employee-attendances.register')<section class="mt-5 max-w-3xl rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-7"><h2 class="text-lg font-bold">Registrar salida</h2><p class="mt-1 text-sm text-slate-600">Para un turno nocturno, una hora menor a la entrada se interpreta como salida del dia siguiente.</p><form method="POST" action="{{ route('employee-attendances.checkout', $attendance) }}" class="mt-5 grid gap-5 sm:grid-cols-2">@csrf @method('PATCH')<div><label for="exit_time" class="text-sm font-medium text-slate-700">Hora de salida</label><input id="exit_time" name="exit_time" type="time" value="{{ old('exit_time', now()->format('H:i')) }}" required class="mt-1 block w-full rounded-lg border-slate-300"><x-field-error name="exit_time" /></div><div><label for="observations" class="text-sm font-medium text-slate-700">Observaciones</label><input id="observations" name="observations" value="{{ old('observations', $attendance->observations) }}" class="mt-1 block w-full rounded-lg border-slate-300"><x-field-error name="observations" /></div><div class="sm:col-span-2"><button type="submit" class="rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-indigo-500">Registrar salida</button></div></form></section>@endcan@endif
@endsection
