@extends('layouts.admin')

@section('title', 'Horarios')

@section('content')
    <div class="mb-6 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-semibold uppercase tracking-widest text-indigo-600">Actividades</p><h1 class="mt-1 text-3xl font-bold tracking-tight">Horarios</h1><p class="mt-2 text-slate-600">Horarios recurrentes de las clases y actividades configuradas.</p></div>@can('schedules.manage')<a href="{{ route('class-schedules.create') }}" class="rounded-lg bg-indigo-600 px-4 py-2.5 text-center text-sm font-semibold text-white hover:bg-indigo-500">Nuevo horario</a>@endcan</div>
    <form method="GET" class="mb-5 flex flex-col gap-3 rounded-xl bg-white p-4 shadow-sm ring-1 ring-slate-200 sm:flex-row sm:items-end"><div class="sm:w-80"><label for="branch_id" class="text-sm font-medium text-slate-700">Filtrar por sucursal</label><select id="branch_id" name="branch_id" class="mt-1 block w-full rounded-lg border-slate-300"><option value="">Todas las sucursales</option>@foreach ($branches as $branch)<option value="{{ $branch->id }}" @selected($selectedBranchId === $branch->id)>{{ $branch->name }}</option>@endforeach</select></div><div class="flex gap-2"><button type="submit" class="rounded-lg bg-slate-800 px-4 py-2.5 text-sm font-semibold text-white hover:bg-slate-700">Filtrar</button><a href="{{ route('class-schedules.index') }}" class="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50">Limpiar</a></div></form>
    <div class="overflow-hidden rounded-xl bg-white shadow-sm ring-1 ring-slate-200"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50 text-left text-xs font-semibold uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3">Actividad</th><th class="px-5 py-3">Sucursal</th><th class="px-5 py-3">Día</th><th class="px-5 py-3">Horario</th><th class="px-5 py-3">Estado</th><th class="px-5 py-3"><span class="sr-only">Acciones</span></th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($schedules as $schedule)<tr><td class="px-5 py-4"><a href="{{ route('gym-classes.show', $schedule->gymClass) }}" class="font-semibold text-indigo-700 hover:text-indigo-500">{{ $schedule->gymClass->name }}</a></td><td class="px-5 py-4 text-slate-600">{{ $schedule->gymClass->branch->name }}</td><td class="px-5 py-4 text-slate-600">{{ ucfirst($schedule->day_of_week) }}</td><td class="px-5 py-4 text-slate-600">{{ substr($schedule->start_time, 0, 5) }} – {{ substr($schedule->end_time, 0, 5) }}</td><td class="px-5 py-4"><x-status-badge :active="$schedule->is_active" /></td><td class="px-5 py-4 text-right">@can('schedules.manage')<a href="{{ route('class-schedules.edit', $schedule) }}" class="text-sm font-medium text-indigo-700 hover:text-indigo-500">Editar</a>@endcan</td></tr>@empty<tr><td colspan="6" class="px-5 py-10 text-center text-slate-500">No hay horarios registrados.</td></tr>@endforelse</tbody></table></div>@if ($schedules->hasPages())<div class="border-t border-slate-200 px-5 py-4">{{ $schedules->links() }}</div>@endif</div>
@endsection
