@extends('layouts.admin')

@section('title', 'Membresía de '.$clientMembership->client->first_name)

@section('content')
    <div class="mb-6 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><a href="{{ route('client-memberships.index') }}" class="text-sm font-medium text-indigo-700 hover:text-indigo-500">← Volver a membresías de clientes</a><div class="mt-3 flex flex-wrap items-center gap-3"><h1 class="text-3xl font-bold tracking-tight">{{ $clientMembership->membershipType->name }}</h1><x-status-badge :active="$clientMembership->status === \App\ClientMembershipStatus::Active" :active-label="$clientMembership->status->value" :inactive-label="$clientMembership->status->value" /></div><p class="mt-2 text-slate-600">{{ $clientMembership->client->first_name }} {{ $clientMembership->client->last_name }}</p></div>@can('client-memberships.manage')<a href="{{ route('client-memberships.edit', $clientMembership) }}" class="rounded-lg bg-indigo-600 px-4 py-2.5 text-center text-sm font-semibold text-white hover:bg-indigo-500">Editar</a>@endcan</div>
    <section class="max-w-4xl rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-7"><dl class="grid gap-5 sm:grid-cols-2"><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Cliente</dt><dd class="mt-1"><a href="{{ route('clients.show', $clientMembership->client) }}" class="font-medium text-indigo-700 hover:text-indigo-500">{{ $clientMembership->client->first_name }} {{ $clientMembership->client->last_name }}</a></dd></div><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Sucursal</dt><dd class="mt-1 text-slate-800">{{ $clientMembership->client->branch->name }}</dd></div><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Vigencia</dt><dd class="mt-1 text-slate-800">{{ $clientMembership->start_date->format('d/m/Y') }} – {{ $clientMembership->end_date->format('d/m/Y') }}</dd></div><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Precio aplicado</dt><dd class="mt-1 text-slate-800">{{ number_format((float) $clientMembership->applied_price, 2) }}</dd></div><div class="sm:col-span-2"><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Observaciones</dt><dd class="mt-1 whitespace-pre-line text-slate-800">{{ $clientMembership->observations ?: 'Sin observaciones.' }}</dd></div></dl></section>
    @can('client-memberships.manage')@if ($clientMembership->status !== \App\ClientMembershipStatus::Cancelled)<form method="POST" action="{{ route('client-memberships.destroy', $clientMembership) }}" class="mt-5" onsubmit="return confirm('¿Deseas cancelar esta membresía?');">@csrf @method('DELETE')<button class="rounded-lg border border-red-300 px-4 py-2.5 text-sm font-semibold text-red-700 hover:bg-red-50">Cancelar membresía</button></form>@endif@endcan
@endsection
