@extends('layouts.admin')

@section('title', $branch->name)

@section('content')
    <div class="mb-6 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><a href="{{ route('branches.index') }}" class="text-sm font-medium text-indigo-700 hover:text-indigo-500">← Volver a sucursales</a><div class="mt-3 flex flex-wrap items-center gap-3"><h1 class="text-3xl font-bold tracking-tight">{{ $branch->name }}</h1><x-status-badge :active="$branch->is_active" /></div><p class="mt-2 font-mono text-sm text-slate-500">{{ $branch->code }}</p></div>@can('branches.manage')<a href="{{ route('branches.edit', $branch) }}" class="rounded-lg bg-indigo-600 px-4 py-2.5 text-center text-sm font-semibold text-white hover:bg-indigo-500">Editar</a>@endcan</div>
    <div class="grid gap-5 lg:grid-cols-[2fr_1fr]"><section class="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-7"><h2 class="text-lg font-bold">Información de la sucursal</h2><dl class="mt-5 grid gap-5 sm:grid-cols-2"><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Dirección</dt><dd class="mt-1 text-slate-800">{{ $branch->address ?: 'No registrada' }}</dd></div><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Teléfono</dt><dd class="mt-1 text-slate-800">{{ $branch->phone ?: 'No registrado' }}</dd></div><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Horario</dt><dd class="mt-1 text-slate-800">{{ $branch->opening_time ? substr($branch->opening_time, 0, 5) : '—' }} – {{ $branch->closing_time ? substr($branch->closing_time, 0, 5) : '—' }}</dd></div></dl></section><aside class="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h2 class="text-lg font-bold">Servicios asociados</h2><ul class="mt-4 grid gap-2">@forelse ($branch->services as $service)<li class="rounded-lg bg-slate-50 px-3 py-2 text-sm text-slate-700">{{ $service->name }}</li>@empty<li class="text-sm text-slate-500">No hay servicios asociados.</li>@endforelse</ul></aside></div>
    @can('branches.manage')<div class="mt-5 flex flex-wrap gap-3"><form method="POST" action="{{ route('branches.toggle-status', $branch) }}" onsubmit="return confirm('¿Deseas cambiar el estado de esta sucursal?');">@csrf @method('PATCH')<button class="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50">{{ $branch->is_active ? 'Desactivar' : 'Activar' }}</button></form>@if ($branch->is_active)<form method="POST" action="{{ route('branches.destroy', $branch) }}" onsubmit="return confirm('¿Deseas desactivar esta sucursal?');">@csrf @method('DELETE')<button class="rounded-lg border border-red-300 px-4 py-2.5 text-sm font-semibold text-red-700 hover:bg-red-50">Desactivar</button></form>@endif</div>@endcan
@endsection
