@extends('layouts.admin')

@section('title', 'Registrar venta')

@section('content')
    @php($details = old('details', [['concept_type' => 'other', 'concept_reference_id' => '', 'description' => '', 'quantity' => 1, 'unit_price' => '']]))
    <div class="mb-6"><a href="{{ route('sales.index') }}" class="text-sm font-medium text-indigo-700 hover:text-indigo-500">← Volver a ventas</a><h1 class="mt-3 text-3xl font-bold tracking-tight">Registrar venta</h1><p class="mt-2 text-slate-600">Los importes se calculan en el servidor al confirmar la venta.</p></div>
    <form method="POST" action="{{ route('sales.store') }}" class="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-7">
        @csrf
        <div class="grid gap-5 sm:grid-cols-2">
            <div><label for="client_id" class="text-sm font-medium text-slate-700">Cliente (opcional)</label><select id="client_id" name="client_id" class="mt-1 block w-full rounded-lg border-slate-300"><option value="">Venta sin cliente</option>@foreach ($clients as $client)<option value="{{ $client->id }}" @selected((int) old('client_id') === $client->id)>{{ $client->last_name }}, {{ $client->first_name }} · {{ $client->code }}</option>@endforeach</select><x-field-error name="client_id" /></div>
            <div><label for="branch_id" class="text-sm font-medium text-slate-700">Sucursal</label><select id="branch_id" name="branch_id" required class="mt-1 block w-full rounded-lg border-slate-300"><option value="">Selecciona una sucursal</option>@foreach ($branches as $branch)<option value="{{ $branch->id }}" @selected((int) old('branch_id') === $branch->id)>{{ $branch->name }}</option>@endforeach</select><x-field-error name="branch_id" /></div>
            <div><label for="sale_date" class="text-sm font-medium text-slate-700">Fecha</label><input id="sale_date" name="sale_date" type="date" value="{{ old('sale_date', now()->toDateString()) }}" required class="mt-1 block w-full rounded-lg border-slate-300"><x-field-error name="sale_date" /></div>
            <div><label for="discount" class="text-sm font-medium text-slate-700">Descuento manual</label><input id="discount" name="discount" type="number" min="0" step="0.01" value="{{ old('discount', 0) }}" class="mt-1 block w-full rounded-lg border-slate-300"><x-field-error name="discount" /></div>
            <div><label for="payment_method" class="text-sm font-medium text-slate-700">Método de pago</label><select id="payment_method" name="payment_method" required class="mt-1 block w-full rounded-lg border-slate-300">@foreach ($methods as $method)<option value="{{ $method->value }}" @selected(old('payment_method', 'cash') === $method->value)>{{ ucfirst($method->value) }}</option>@endforeach</select><x-field-error name="payment_method" /></div>
            <div><label for="reference" class="text-sm font-medium text-slate-700">Referencia de pago</label><input id="reference" name="reference" type="text" value="{{ old('reference') }}" class="mt-1 block w-full rounded-lg border-slate-300"><x-field-error name="reference" /></div>
        </div>
        <div class="mt-7 border-t border-slate-200 pt-6"><div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="text-lg font-bold">Detalle de venta</h2><p class="mt-1 text-sm text-slate-600">Agrega membresías, servicios u otros conceptos.</p></div><button id="add-detail" type="button" class="rounded-lg border border-indigo-600 px-3 py-2 text-sm font-semibold text-indigo-700 hover:bg-indigo-50">Agregar línea</button></div><x-field-error name="details" /><div id="details" class="mt-5 space-y-4">@foreach ($details as $index => $detail)<div class="detail-row rounded-lg border border-slate-200 p-4"><div class="grid gap-4 md:grid-cols-6"><div><label class="text-sm font-medium text-slate-700">Tipo</label><select name="details[{{ $index }}][concept_type]" required class="mt-1 block w-full rounded-lg border-slate-300"><option value="membership" @selected(($detail['concept_type'] ?? '') === 'membership')>Membresía</option><option value="service" @selected(($detail['concept_type'] ?? '') === 'service')>Servicio</option><option value="other" @selected(($detail['concept_type'] ?? '') === 'other')>Otro</option></select><x-field-error name="details.{{ $index }}.concept_type" /></div><div><label class="text-sm font-medium text-slate-700">Ref. (opcional)</label><input name="details[{{ $index }}][concept_reference_id]" type="number" min="1" value="{{ $detail['concept_reference_id'] ?? '' }}" class="mt-1 block w-full rounded-lg border-slate-300"><x-field-error name="details.{{ $index }}.concept_reference_id" /></div><div class="md:col-span-2"><label class="text-sm font-medium text-slate-700">Descripción</label><input name="details[{{ $index }}][description]" type="text" value="{{ $detail['description'] ?? '' }}" required class="mt-1 block w-full rounded-lg border-slate-300"><x-field-error name="details.{{ $index }}.description" /></div><div><label class="text-sm font-medium text-slate-700">Cantidad</label><input name="details[{{ $index }}][quantity]" type="number" min="0.01" step="0.01" value="{{ $detail['quantity'] ?? 1 }}" required class="mt-1 block w-full rounded-lg border-slate-300"><x-field-error name="details.{{ $index }}.quantity" /></div><div><label class="text-sm font-medium text-slate-700">Precio unitario</label><input name="details[{{ $index }}][unit_price]" type="number" min="0" step="0.01" value="{{ $detail['unit_price'] ?? '' }}" required class="mt-1 block w-full rounded-lg border-slate-300"><x-field-error name="details.{{ $index }}.unit_price" /></div></div><button type="button" data-remove-detail class="mt-3 text-sm font-medium text-red-700 hover:text-red-500">Quitar línea</button></div>@endforeach</div></div>
        <div class="mt-5"><label for="observations" class="text-sm font-medium text-slate-700">Observaciones del pago</label><textarea id="observations" name="observations" rows="3" class="mt-1 block w-full rounded-lg border-slate-300">{{ old('observations') }}</textarea><x-field-error name="observations" /></div>
        <div class="mt-7 flex flex-wrap gap-3"><button type="submit" class="rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-indigo-500">Confirmar venta</button><a href="{{ route('sales.index') }}" class="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50">Cancelar</a></div>
    </form>
    <template id="detail-template"><div class="detail-row rounded-lg border border-slate-200 p-4"><div class="grid gap-4 md:grid-cols-6"><div><label class="text-sm font-medium text-slate-700">Tipo</label><select name="details[__INDEX__][concept_type]" required class="mt-1 block w-full rounded-lg border-slate-300"><option value="membership">Membresía</option><option value="service">Servicio</option><option value="other" selected>Otro</option></select></div><div><label class="text-sm font-medium text-slate-700">Ref. (opcional)</label><input name="details[__INDEX__][concept_reference_id]" type="number" min="1" class="mt-1 block w-full rounded-lg border-slate-300"></div><div class="md:col-span-2"><label class="text-sm font-medium text-slate-700">Descripción</label><input name="details[__INDEX__][description]" type="text" required class="mt-1 block w-full rounded-lg border-slate-300"></div><div><label class="text-sm font-medium text-slate-700">Cantidad</label><input name="details[__INDEX__][quantity]" type="number" min="0.01" step="0.01" value="1" required class="mt-1 block w-full rounded-lg border-slate-300"></div><div><label class="text-sm font-medium text-slate-700">Precio unitario</label><input name="details[__INDEX__][unit_price]" type="number" min="0" step="0.01" required class="mt-1 block w-full rounded-lg border-slate-300"></div></div><button type="button" data-remove-detail class="mt-3 text-sm font-medium text-red-700 hover:text-red-500">Quitar línea</button></div></template>
    <script>
        const detailsContainer = document.getElementById('details');
        const detailTemplate = document.getElementById('detail-template');
        let detailIndex = {{ count($details) }};
        document.getElementById('add-detail').addEventListener('click', () => {
            detailsContainer.insertAdjacentHTML('beforeend', detailTemplate.innerHTML.replaceAll('__INDEX__', detailIndex));
            detailIndex += 1;
        });
        detailsContainer.addEventListener('click', (event) => {
            if (event.target.matches('[data-remove-detail]') && detailsContainer.children.length > 1) {
                event.target.closest('.detail-row').remove();
            }
        });
    </script>
@endsection
