@extends('layouts.admin')

@section('title', $employee->fullName())

@section('content')
    <div class="mb-6 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
        <div><a href="{{ route('employees.index') }}" class="text-sm font-medium text-indigo-700 hover:text-indigo-500">Volver a empleados</a><div class="mt-3 flex flex-wrap items-center gap-3"><h1 class="text-3xl font-bold tracking-tight">{{ $employee->fullName() }}</h1><x-status-badge :active="$employee->status === \App\EmployeeStatus::Active" /></div><p class="mt-2 font-mono text-sm text-slate-500">{{ $employee->code }}</p></div>
        <div class="flex flex-wrap gap-2">@can('employee-attendances.register')<a href="{{ route('employee-attendances.create', ['employee_id' => $employee->id]) }}" class="rounded-lg border border-indigo-600 px-4 py-2.5 text-sm font-semibold text-indigo-700 hover:bg-indigo-50">Registrar asistencia</a>@endcan @can('employees.manage')<a href="{{ route('employees.edit', $employee) }}" class="rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-indigo-500">Editar</a>@endcan</div>
    </div>

    <div class="grid gap-5 lg:grid-cols-[2fr_1fr]">
        <section class="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-7"><h2 class="text-lg font-bold">Informacion laboral</h2><dl class="mt-5 grid gap-5 sm:grid-cols-2"><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Puesto</dt><dd class="mt-1 text-slate-800">{{ $employee->position->name }}</dd></div><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Sucursal</dt><dd class="mt-1 text-slate-800">{{ $employee->branch->name }}</dd></div><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Contratacion</dt><dd class="mt-1 text-slate-800">{{ $employee->hired_at->format('d/m/Y') }}</dd></div><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Usuario asociado</dt><dd class="mt-1 text-slate-800">{{ $employee->user ? $employee->user->name.' ('.$employee->user->email.')' : 'Sin cuenta asociada' }}</dd></div><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Telefono</dt><dd class="mt-1 text-slate-800">{{ $employee->phone ?: 'No registrado' }}</dd></div><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Correo</dt><dd class="mt-1 text-slate-800">{{ $employee->email ?: 'No registrado' }}</dd></div></dl></section>
        <aside class="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h2 class="text-lg font-bold">Turno actual</h2>@if ($currentShiftAssignment)<p class="mt-3 font-semibold text-slate-800">{{ $currentShiftAssignment->workShift->name }}</p><p class="mt-1 text-sm text-slate-600">{{ substr($currentShiftAssignment->workShift->start_time, 0, 5) }} - {{ substr($currentShiftAssignment->workShift->end_time, 0, 5) }}</p>@else<p class="mt-3 text-sm text-slate-500">No tiene un turno vigente.</p>@endif<h2 class="mt-6 text-lg font-bold">Ultima asistencia</h2>@if ($employee->attendances->first())<p class="mt-2 text-sm text-slate-700">{{ $employee->attendances->first()->attendance_date->format('d/m/Y') }} · {{ substr($employee->attendances->first()->entry_time, 0, 5) }}</p>@else<p class="mt-2 text-sm text-slate-500">Sin asistencias registradas.</p>@endif</aside>
    </div>

    <section class="mt-5 overflow-hidden rounded-xl bg-white shadow-sm ring-1 ring-slate-200"><div class="flex items-center justify-between border-b border-slate-200 px-5 py-4"><h2 class="text-lg font-bold">Asignaciones de turno</h2>@can('work-shifts.manage')<a href="{{ route('employee-shift-assignments.create', ['employee_id' => $employee->id]) }}" class="text-sm font-medium text-indigo-700 hover:text-indigo-500">Asignar turno</a>@endcan</div><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50 text-left text-xs font-semibold uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3">Turno</th><th class="px-5 py-3">Vigencia</th><th class="px-5 py-3">Dia</th><th class="px-5 py-3">Estado</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($employee->shiftAssignments as $assignment)<tr><td class="px-5 py-4 text-slate-800">{{ $assignment->workShift->name }} · {{ substr($assignment->workShift->start_time, 0, 5) }}-{{ substr($assignment->workShift->end_time, 0, 5) }}</td><td class="px-5 py-4 text-slate-600">{{ $assignment->effective_from->format('d/m/Y') }} - {{ $assignment->effective_until?->format('d/m/Y') ?? 'Sin fin' }}</td><td class="px-5 py-4 text-slate-600">{{ $assignment->day_of_week ? ucfirst($assignment->day_of_week) : 'Todos' }}</td><td class="px-5 py-4"><x-status-badge :active="$assignment->is_active" /></td></tr>@empty<tr><td colspan="4" class="px-5 py-8 text-center text-slate-500">No hay turnos asignados.</td></tr>@endforelse</tbody></table></div></section>

    <section class="mt-5 overflow-hidden rounded-xl bg-white shadow-sm ring-1 ring-slate-200"><div class="border-b border-slate-200 px-5 py-4"><h2 class="text-lg font-bold">Historial de asistencias</h2></div><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50 text-left text-xs font-semibold uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3">Fecha</th><th class="px-5 py-3">Turno</th><th class="px-5 py-3">Entrada</th><th class="px-5 py-3">Salida</th><th class="px-5 py-3">Duracion</th><th class="px-5 py-3"><span class="sr-only">Ver</span></th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($employee->attendances as $attendance)<tr><td class="px-5 py-4 text-slate-600">{{ $attendance->attendance_date->format('d/m/Y') }}</td><td class="px-5 py-4 text-slate-600">{{ $attendance->workShift?->name ?? 'Sin turno' }}</td><td class="px-5 py-4 text-slate-600">{{ substr($attendance->entry_time, 0, 5) }}</td><td class="px-5 py-4 text-slate-600">{{ $attendance->exit_time ? substr($attendance->exit_time, 0, 5) : 'Pendiente' }}</td><td class="px-5 py-4 text-slate-800">{{ $attendance->workedDuration() ?? 'Pendiente' }}</td><td class="px-5 py-4 text-right"><a href="{{ route('employee-attendances.show', $attendance) }}" class="text-sm font-medium text-indigo-700 hover:text-indigo-500">Ver</a></td></tr>@empty<tr><td colspan="6" class="px-5 py-8 text-center text-slate-500">No hay asistencias registradas.</td></tr>@endforelse</tbody></table></div></section>

    @if ($employee->gymClasses->isNotEmpty())<section class="mt-5 rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h2 class="text-lg font-bold">Clases asignadas</h2><div class="mt-4 flex flex-wrap gap-2">@foreach ($employee->gymClasses as $gymClass)<a href="{{ route('gym-classes.show', $gymClass) }}" class="rounded-lg border border-indigo-200 px-3 py-2 text-sm font-medium text-indigo-700 hover:bg-indigo-50">{{ $gymClass->name }} · {{ $gymClass->branch->name }}</a>@endforeach</div></section>@endif

    @can('employees.manage')<div class="mt-5"><form method="POST" action="{{ route('employees.toggle-status', $employee) }}">@csrf @method('PATCH')<button class="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50">{{ $employee->status === \App\EmployeeStatus::Active ? 'Desactivar empleado' : 'Activar empleado' }}</button></form></div>@endcan
@endsection
