@extends('layouts.admin')

@section('title', $gymClass->name)

@section('content')
    <div class="mb-6 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><a href="{{ route('gym-classes.index') }}" class="text-sm font-medium text-indigo-700 hover:text-indigo-500">← Volver a clases</a><div class="mt-3 flex flex-wrap items-center gap-3"><h1 class="text-3xl font-bold tracking-tight">{{ $gymClass->name }}</h1><x-status-badge :active="$gymClass->is_active" /></div><p class="mt-2 text-slate-600">{{ ucfirst($gymClass->type) }} · {{ $gymClass->branch->name }}</p></div><div class="flex flex-wrap gap-2">@can('schedules.manage')<a href="{{ route('class-schedules.create', ['gym_class_id' => $gymClass->id]) }}" class="rounded-lg border border-indigo-600 px-4 py-2.5 text-sm font-semibold text-indigo-700 hover:bg-indigo-50">Agregar horario</a>@endcan @can('classes.manage')<a href="{{ route('gym-classes.edit', $gymClass) }}" class="rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-indigo-500">Editar</a>@endcan</div></div>
    <div class="grid gap-5 lg:grid-cols-[2fr_1fr]"><section class="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-7"><h2 class="text-lg font-bold">Información de la actividad</h2><p class="mt-4 whitespace-pre-line text-slate-700">{{ $gymClass->description ?: 'Sin descripción registrada.' }}</p></section><aside class="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h2 class="text-lg font-bold">Capacidad</h2><p class="mt-3 text-3xl font-bold">{{ $gymClass->maximum_capacity }}</p><p class="mt-1 text-sm text-slate-600">participantes por horario y fecha.</p></aside></div>
    <section class="mt-5 overflow-hidden rounded-xl bg-white shadow-sm ring-1 ring-slate-200"><div class="flex items-center justify-between border-b border-slate-200 px-5 py-4"><div><h2 class="text-lg font-bold">Horarios</h2><p class="mt-1 text-sm text-slate-600">Cupos calculados para hoy.</p></div>@can('schedules.manage')<a href="{{ route('class-schedules.create', ['gym_class_id' => $gymClass->id]) }}" class="text-sm font-medium text-indigo-700 hover:text-indigo-500">Nuevo horario</a>@endcan</div><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50 text-left text-xs font-semibold uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3">Día</th><th class="px-5 py-3">Horario</th><th class="px-5 py-3">Inscritos</th><th class="px-5 py-3">Disponibles</th><th class="px-5 py-3">Estado</th><th class="px-5 py-3"><span class="sr-only">Editar</span></th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($gymClass->schedules as $schedule)<tr><td class="px-5 py-4 text-slate-700">{{ ucfirst($schedule->day_of_week) }}</td><td class="px-5 py-4 text-slate-600">{{ substr($schedule->start_time, 0, 5) }} – {{ substr($schedule->end_time, 0, 5) }}</td><td class="px-5 py-4 text-slate-600">{{ $schedule->enrolled_today_count }}</td><td class="px-5 py-4 font-medium text-slate-800">{{ max(0, $gymClass->maximum_capacity - $schedule->enrolled_today_count) }}</td><td class="px-5 py-4"><x-status-badge :active="$schedule->is_active" /></td><td class="px-5 py-4 text-right">@can('schedules.manage')<a href="{{ route('class-schedules.edit', $schedule) }}" class="text-sm font-medium text-indigo-700 hover:text-indigo-500">Editar</a>@endcan</td></tr>@empty<tr><td colspan="6" class="px-5 py-8 text-center text-slate-500">No hay horarios configurados.</td></tr>@endforelse</tbody></table></div></section>
    <section class="mt-5 overflow-hidden rounded-xl bg-white shadow-sm ring-1 ring-slate-200"><div class="border-b border-slate-200 px-5 py-4"><h2 class="text-lg font-bold">Participantes recientes</h2></div><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50 text-left text-xs font-semibold uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3">Cliente</th><th class="px-5 py-3">Fecha</th><th class="px-5 py-3">Horario</th><th class="px-5 py-3">Estado</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($gymClass->enrollments as $enrollment)<tr><td class="px-5 py-4"><a href="{{ route('clients.show', $enrollment->client) }}" class="font-medium text-indigo-700 hover:text-indigo-500">{{ $enrollment->client->first_name }} {{ $enrollment->client->last_name }}</a></td><td class="px-5 py-4 text-slate-600">{{ $enrollment->enrollment_date->format('d/m/Y') }}</td><td class="px-5 py-4 text-slate-600">{{ ucfirst($enrollment->gymClassSchedule->day_of_week) }} · {{ substr($enrollment->gymClassSchedule->start_time, 0, 5) }}</td><td class="px-5 py-4"><span class="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-700">{{ ucfirst($enrollment->status->value) }}</span></td></tr>@empty<tr><td colspan="4" class="px-5 py-8 text-center text-slate-500">No hay participantes registrados.</td></tr>@endforelse</tbody></table></div></section>
    @can('classes.manage')<div class="mt-5"><form method="POST" action="{{ route('gym-classes.toggle-status', $gymClass) }}">@csrf @method('PATCH')<button class="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50">{{ $gymClass->is_active ? 'Desactivar actividad' : 'Activar actividad' }}</button></form></div>@endcan
@endsection
