<!DOCTYPE html>
<html lang="es">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{{ config('app.name') }} · @yield('title', 'Administración')</title>@vite(['resources/css/app.css', 'resources/js/app.js'])</head>
<body class="min-h-screen bg-slate-100 text-slate-900"><div class="min-h-screen lg:grid lg:grid-cols-[17rem_1fr]"><aside class="bg-slate-900 p-4 text-slate-100 lg:p-6"><a href="{{ route('dashboard') }}" class="mb-6 block text-xl font-bold text-white">Gimnasio · Administración</a><nav class="max-h-[calc(100vh-7rem)] space-y-1 overflow-y-auto" aria-label="Navegación principal">
@can('dashboard.view')<a href="{{ route('dashboard') }}" @class(['nav-link', 'bg-slate-700 text-white' => request()->routeIs('dashboard'), 'text-slate-300 hover:bg-slate-800' => ! request()->routeIs('dashboard')])>Dashboard</a>@endcan
<p class="section-title">Configuración</p>@can('branches.view')<a href="{{ route('branches.index') }}" @class(['nav-link', 'active' => request()->routeIs('branches.*')])>Sucursales</a>@endcan @can('services.view')<a href="{{ route('services.index') }}" @class(['nav-link', 'active' => request()->routeIs('services.*')])>Servicios</a>@endcan
<p class="section-title">Clientes</p>@can('clients.view')<a href="{{ route('clients.index') }}" @class(['nav-link', 'active' => request()->routeIs('clients.*')])>Clientes</a>@endcan @can('membership-types.view')<a href="{{ route('membership-types.index') }}" @class(['nav-link', 'active' => request()->routeIs('membership-types.*')])>Membresías</a>@endcan @can('benefits.view')<a href="{{ route('benefits.index') }}" @class(['nav-link', 'active' => request()->routeIs('benefits.*')])>Beneficios</a>@endcan @can('client-memberships.view')<a href="{{ route('client-memberships.index') }}" @class(['nav-link', 'active' => request()->routeIs('client-memberships.*')])>Membresías de clientes</a>@endcan @can('renewals.view')<a href="{{ route('renewals.index') }}" @class(['nav-link', 'active' => request()->routeIs('renewals.*')])>Renovaciones</a>@endcan @can('referrals.view')<a href="{{ route('referrals.index') }}" @class(['nav-link', 'active' => request()->routeIs('referrals.*')])>Referidos</a>@endcan
<p class="section-title">Comercial</p>@can('payments.view')<a href="{{ route('payments.index') }}" @class(['nav-link', 'active' => request()->routeIs('payments.*')])>Pagos</a>@endcan @can('sales.view')<a href="{{ route('sales.index') }}" @class(['nav-link', 'active' => request()->routeIs('sales.*')])>Ventas</a>@endcan @can('commercial-partners.view')<a href="{{ route('commercial-partners.index') }}" @class(['nav-link', 'active' => request()->routeIs('commercial-partners.*')])>Terceros</a>@endcan @can('third-party-items.view')<a href="{{ route('third-party-items.index') }}" @class(['nav-link', 'active' => request()->routeIs('third-party-items.*')])>Productos externos</a>@endcan @can('discounts.view')<a href="{{ route('discounts.index') }}" @class(['nav-link', 'active' => request()->routeIs('discounts.*')])>Descuentos</a>@endcan
<p class="section-title">Personal</p>@can('employees.view')<a href="{{ route('employees.index') }}" @class(['nav-link', 'active' => request()->routeIs('employees.*')])>Empleados</a>@endcan @can('positions.manage')<a href="{{ route('positions.index') }}" @class(['nav-link', 'active' => request()->routeIs('positions.*')])>Puestos</a>@endcan @can('work-shifts.manage')<a href="{{ route('work-shifts.index') }}" @class(['nav-link', 'active' => request()->routeIs('work-shifts.*', 'employee-shift-assignments.*')])>Turnos</a>@endcan @can('employee-attendances.view')<a href="{{ route('employee-attendances.index') }}" @class(['nav-link', 'active' => request()->routeIs('employee-attendances.*')])>Asistencia</a>@endcan @can('view_bonuses')<a href="{{ route('employee-bonuses.index') }}" @class(['nav-link', 'active' => request()->routeIs('employee-bonuses.*')])>Bonos</a>@endcan
<p class="section-title">Operaciones</p>@can('classes.view')<a href="{{ route('gym-classes.index') }}" @class(['nav-link', 'active' => request()->routeIs('gym-classes.*')])>Clases</a>@endcan @can('schedules.view')<a href="{{ route('class-schedules.index') }}" @class(['nav-link', 'active' => request()->routeIs('class-schedules.*')])>Horarios</a>@endcan @can('enrollments.view')<a href="{{ route('class-enrollments.index') }}" @class(['nav-link', 'active' => request()->routeIs('class-enrollments.*')])>Participantes</a>@endcan
<p class="section-title">Inventario y compras</p>@can('view_inventory')<a href="{{ route('inventory-items.index') }}" @class(['nav-link', 'active' => request()->routeIs('inventory-items.*')])>Inventario</a>@endcan @can('view_maintenance')<a href="{{ route('equipment-maintenances.index') }}" @class(['nav-link', 'active' => request()->routeIs('equipment-maintenances.*')])>Mantenimiento</a>@endcan @can('view_suppliers')<a href="{{ route('suppliers.index') }}" @class(['nav-link', 'active' => request()->routeIs('suppliers.*')])>Proveedores</a>@endcan @can('view_purchases')<a href="{{ route('purchase-orders.index') }}" @class(['nav-link', 'active' => request()->routeIs('purchase-orders.*', 'quality-certificates.*')])>Órdenes de compra y certificados</a>@endcan
<p class="section-title">Reportes</p>@can('view_reports')<a href="{{ route('reports.index') }}" @class(['nav-link', 'active' => request()->routeIs('reports.*')])>Reportes</a>@endcan
</nav></aside><main class="min-w-0"><header class="flex flex-col gap-3 border-b border-slate-200 bg-white px-5 py-4 sm:flex-row sm:items-center sm:justify-between sm:px-8"><div><p class="text-sm font-medium">{{ $authenticatedUser->name }}</p><p class="text-xs text-slate-500">{{ $authenticatedUser->roles->pluck('name')->join(' · ') }}</p></div><form method="POST" action="{{ route('logout') }}">@csrf<button type="submit" class="rounded-lg border border-slate-300 px-3 py-2 text-sm">Cerrar sesión</button></form></header><div class="mx-auto max-w-7xl p-5 sm:p-8">@if(session('success'))<div class="mb-6 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800" role="status">{{ session('success') }}</div>@endif @if($errors->any())<div class="mb-6 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800" role="alert">Revisa los campos marcados para continuar.</div>@endif @yield('content')</div></main></div><style>.nav-link{display:block;border-radius:.5rem;padding:.5rem .75rem;font-size:.875rem;font-weight:500}.nav-link.active{background-color:#334155;color:#fff}.section-title{margin-top:1rem;padding:0 .75rem;font-size:.6875rem;font-weight:600;text-transform:uppercase;letter-spacing:.08em;color:#64748b}</style></body></html>
