@extends('layouts.admin')

@section('title', $commercialPartner ? 'Editar tercero' : 'Nuevo tercero')

@section('content')
    <div class="mb-6"><a href="{{ route('commercial-partners.index') }}" class="text-sm font-medium text-indigo-700 hover:text-indigo-500">Volver a terceros</a><h1 class="mt-3 text-3xl font-bold tracking-tight">{{ $commercialPartner ? 'Editar tercero' : 'Nuevo tercero' }}</h1></div>
    <form method="POST" action="{{ $commercialPartner ? route('commercial-partners.update', $commercialPartner) : route('commercial-partners.store') }}" class="max-w-4xl rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-7">@csrf @if ($commercialPartner) @method('PUT') @endif
        <div class="grid gap-5 sm:grid-cols-2"><div><label for="name" class="text-sm font-medium text-slate-700">Nombre</label><input id="name" name="name" value="{{ old('name', $commercialPartner?->name) }}" required class="mt-1 block w-full rounded-lg border-slate-300"><x-field-error name="name" /></div><div><label for="type" class="text-sm font-medium text-slate-700">Tipo</label><select id="type" name="type" required class="mt-1 block w-full rounded-lg border-slate-300"><option value="product" @selected(old('type', $commercialPartner?->type->value) === 'product')>Productos</option><option value="service" @selected(old('type', $commercialPartner?->type->value) === 'service')>Servicios</option><option value="mixed" @selected(old('type', $commercialPartner?->type->value) === 'mixed')>Mixto</option></select><x-field-error name="type" /></div><div><label for="contact" class="text-sm font-medium text-slate-700">Contacto</label><input id="contact" name="contact" value="{{ old('contact', $commercialPartner?->contact) }}" class="mt-1 block w-full rounded-lg border-slate-300"><x-field-error name="contact" /></div><div><label for="phone" class="text-sm font-medium text-slate-700">Telefono</label><input id="phone" name="phone" value="{{ old('phone', $commercialPartner?->phone) }}" class="mt-1 block w-full rounded-lg border-slate-300"><x-field-error name="phone" /></div><div class="sm:col-span-2"><label for="email" class="text-sm font-medium text-slate-700">Correo electronico</label><input id="email" name="email" type="email" value="{{ old('email', $commercialPartner?->email) }}" class="mt-1 block w-full rounded-lg border-slate-300"><x-field-error name="email" /></div><div class="sm:col-span-2"><label for="observations" class="text-sm font-medium text-slate-700">Observaciones</label><textarea id="observations" name="observations" rows="4" class="mt-1 block w-full rounded-lg border-slate-300">{{ old('observations', $commercialPartner?->observations) }}</textarea><x-field-error name="observations" /></div><label class="flex items-center gap-2 text-sm text-slate-700 sm:col-span-2"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $commercialPartner?->is_active ?? true)) class="rounded border-slate-300 text-indigo-600">Tercero activo</label></div>
        <div class="mt-7 flex flex-wrap gap-3"><button type="submit" class="rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-indigo-500">{{ $commercialPartner ? 'Guardar cambios' : 'Crear tercero' }}</button><a href="{{ $commercialPartner ? route('commercial-partners.show', $commercialPartner) : route('commercial-partners.index') }}" class="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50">Cancelar</a></div>
    </form>
@endsection
