@extends('layouts.admin')

@section('title', 'Terceros')

@section('content')
    <div class="mb-6 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
        <div><p class="text-sm font-semibold uppercase tracking-widest text-indigo-600">Catalogo externo</p><h1 class="mt-1 text-3xl font-bold tracking-tight">Terceros comerciales</h1><p class="mt-2 text-slate-600">Empresas y profesionales que ofrecen productos o servicios para venta.</p></div>
        @can('commercial-partners.manage')<a href="{{ route('commercial-partners.create') }}" class="rounded-lg bg-indigo-600 px-4 py-2.5 text-center text-sm font-semibold text-white hover:bg-indigo-500">Nuevo tercero</a>@endcan
    </div>
    <div class="overflow-hidden rounded-xl bg-white shadow-sm ring-1 ring-slate-200"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50 text-left text-xs font-semibold uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3">Tercero</th><th class="px-5 py-3">Tipo</th><th class="px-5 py-3">Contacto</th><th class="px-5 py-3">Catalogo</th><th class="px-5 py-3">Estado</th><th class="px-5 py-3"><span class="sr-only">Acciones</span></th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($commercialPartners as $commercialPartner)<tr><td class="px-5 py-4"><a href="{{ route('commercial-partners.show', $commercialPartner) }}" class="font-semibold text-indigo-700 hover:text-indigo-500">{{ $commercialPartner->name }}</a><p class="mt-1 text-xs text-slate-500">{{ $commercialPartner->email ?: 'Sin correo' }}</p></td><td class="px-5 py-4 text-slate-600">{{ ucfirst($commercialPartner->type->value) }}</td><td class="px-5 py-4 text-slate-600">{{ $commercialPartner->contact ?: 'Sin contacto' }}<br><span class="text-xs text-slate-500">{{ $commercialPartner->phone ?: '' }}</span></td><td class="px-5 py-4 text-slate-600">{{ $commercialPartner->third_party_items_count }}</td><td class="px-5 py-4"><x-status-badge :active="$commercialPartner->is_active" /></td><td class="px-5 py-4 text-right"><a href="{{ route('commercial-partners.show', $commercialPartner) }}" class="text-sm font-medium text-indigo-700 hover:text-indigo-500">Ver</a></td></tr>@empty<tr><td colspan="6" class="px-5 py-10 text-center text-slate-500">No hay terceros comerciales registrados.</td></tr>@endforelse</tbody></table></div>@if ($commercialPartners->hasPages())<div class="border-t border-slate-200 px-5 py-4">{{ $commercialPartners->links() }}</div>@endif</div>
@endsection
