@extends('layouts.admin')

@section('title', $commercialPartner->name)

@section('content')
    <div class="mb-6 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><a href="{{ route('commercial-partners.index') }}" class="text-sm font-medium text-indigo-700 hover:text-indigo-500">Volver a terceros</a><div class="mt-3 flex flex-wrap items-center gap-3"><h1 class="text-3xl font-bold tracking-tight">{{ $commercialPartner->name }}</h1><x-status-badge :active="$commercialPartner->is_active" /></div></div>@can('commercial-partners.manage')<a href="{{ route('commercial-partners.edit', $commercialPartner) }}" class="rounded-lg bg-indigo-600 px-4 py-2.5 text-center text-sm font-semibold text-white hover:bg-indigo-500">Editar</a>@endcan</div>
    <div class="grid gap-5 lg:grid-cols-[2fr_1fr]"><section class="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-7"><h2 class="text-lg font-bold">Informacion comercial</h2><dl class="mt-5 grid gap-5 sm:grid-cols-2"><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Tipo</dt><dd class="mt-1 text-slate-800">{{ ucfirst($commercialPartner->type->value) }}</dd></div><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Contacto</dt><dd class="mt-1 text-slate-800">{{ $commercialPartner->contact ?: 'No registrado' }}</dd></div><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Telefono</dt><dd class="mt-1 text-slate-800">{{ $commercialPartner->phone ?: 'No registrado' }}</dd></div><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Correo</dt><dd class="mt-1 text-slate-800">{{ $commercialPartner->email ?: 'No registrado' }}</dd></div><div class="sm:col-span-2"><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Observaciones</dt><dd class="mt-1 whitespace-pre-line text-slate-800">{{ $commercialPartner->observations ?: 'Sin observaciones.' }}</dd></div></dl></section><aside class="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h2 class="text-lg font-bold">Catalogo asociado</h2><ul class="mt-4 grid gap-2">@forelse ($commercialPartner->thirdPartyItems as $item)<li><a href="{{ route('third-party-items.show', $item) }}" class="block rounded-lg bg-slate-50 px-3 py-2 text-sm font-medium text-indigo-700 hover:text-indigo-500">{{ $item->name }}<span class="block pt-1 text-xs font-normal text-slate-500">{{ $item->branches->pluck('name')->join(', ') ?: 'Sin sucursal' }}</span></a></li>@empty<li class="text-sm text-slate-500">No tiene articulos asociados.</li>@endforelse</ul></aside></div>
    @can('commercial-partners.manage')@if ($commercialPartner->is_active)<form method="POST" action="{{ route('commercial-partners.destroy', $commercialPartner) }}" class="mt-5" onsubmit="return confirm('Deseas desactivar este tercero?');">@csrf @method('DELETE')<button class="rounded-lg border border-red-300 px-4 py-2.5 text-sm font-semibold text-red-700 hover:bg-red-50">Desactivar</button></form>@endif@endcan
@endsection
