@extends('layouts.admin')

@section('title', $benefit->name)

@section('content')
    <div class="mb-6 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><a href="{{ route('benefits.index') }}" class="text-sm font-medium text-indigo-700 hover:text-indigo-500">← Volver a beneficios</a><div class="mt-3 flex flex-wrap items-center gap-3"><h1 class="text-3xl font-bold tracking-tight">{{ $benefit->name }}</h1><x-status-badge :active="$benefit->is_active" /></div></div>@can('benefits.manage')<a href="{{ route('benefits.edit', $benefit) }}" class="rounded-lg bg-indigo-600 px-4 py-2.5 text-center text-sm font-semibold text-white hover:bg-indigo-500">Editar</a>@endcan</div>
    <div class="grid gap-5 lg:grid-cols-[2fr_1fr]"><section class="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-7"><h2 class="text-lg font-bold">Detalle</h2><dl class="mt-5 grid gap-5 sm:grid-cols-2"><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Tipo</dt><dd class="mt-1 text-slate-800">{{ $benefit->benefit_type ?: 'No definido' }}</dd></div><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Valor</dt><dd class="mt-1 text-slate-800">{{ $benefit->value !== null ? number_format((float) $benefit->value, 2) : 'No definido' }}</dd></div><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Límite</dt><dd class="mt-1 text-slate-800">{{ $benefit->usage_limit ?: 'Sin límite' }}</dd></div><div><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Período</dt><dd class="mt-1 text-slate-800">{{ $benefit->usage_period ?: 'No definido' }}</dd></div><div class="sm:col-span-2"><dt class="text-xs font-semibold uppercase tracking-wide text-slate-500">Descripción</dt><dd class="mt-1 whitespace-pre-line text-slate-800">{{ $benefit->description ?: 'Sin descripción registrada.' }}</dd></div></dl></section><aside class="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h2 class="text-lg font-bold">Membresías asociadas</h2><ul class="mt-4 grid gap-2">@forelse ($benefit->membershipTypes as $membershipType)<li><a href="{{ route('membership-types.show', $membershipType) }}" class="block rounded-lg bg-slate-50 px-3 py-2 text-sm font-medium text-indigo-700 hover:text-indigo-500">{{ $membershipType->name }}</a></li>@empty<li class="text-sm text-slate-500">No hay tipos asociados.</li>@endforelse</ul></aside></div>
    @can('benefits.manage')<div class="mt-5 flex flex-wrap gap-3"><form method="POST" action="{{ route('benefits.toggle-status', $benefit) }}" onsubmit="return confirm('¿Deseas cambiar el estado de este beneficio?');">@csrf @method('PATCH')<button class="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50">{{ $benefit->is_active ? 'Desactivar' : 'Activar' }}</button></form>@if ($benefit->is_active)<form method="POST" action="{{ route('benefits.destroy', $benefit) }}" onsubmit="return confirm('¿Deseas desactivar este beneficio?');">@csrf @method('DELETE')<button class="rounded-lg border border-red-300 px-4 py-2.5 text-sm font-semibold text-red-700 hover:bg-red-50">Desactivar</button></form>@endif</div>@endcan
@endsection
